/* ===== 3D 動作示範：動作庫 =====
   pose(t, J, R) 回傳「左側」各骨骼群組的變換（右側由引擎鏡像）。t：0→1。
   J：關節中心（真實模型座標，左側），R：rot(點, 軸, 角度)、mul(...)、tr(位移)、axis(a,b)。
   movers：主動肌（紅）；antag：被拉長的拮抗肌（藍）；opp：表示該肌在對側。 */
window.JOINTS = {"shoulder": [0.1643, 1.3249, -0.0104], "elbow": [0.2097, 1.0545, -0.0174], "latEpi": [0.2403, 1.0644, -0.0251], "medEpi": [0.177, 1.0587, -0.018], "radHead": [0.2308, 1.0406, -0.0149], "ulnHead": [0.2382, 0.8226, 0.0278], "wrist": [0.2562, 0.8208, 0.0293], "sc": [0.0101, 1.3396, 0.0438], "scapC": [0.1165, 1.3135, -0.0435], "acromion": [0.167, 1.3561, -0.0276], "hip": [0.0801, 0.8202, 0.0106], "knee": [0.0725, 0.4229, -0.015], "femLat": [0.1137, 0.4317, -0.0153], "femMed": [0.0321, 0.4376, -0.0187], "ankle": [0.073, 0.0577, -0.0171], "latMall": [0.1042, 0.0404, -0.0358], "medMall": [0.0475, 0.0693, -0.0218], "talus": [0.073, 0.0517, -0.0171], "calc": [0.0808, 0.0212, -0.0734], "mt1": [0.0677, 0.0126, 0.0967], "mt5": [0.1279, 0.0016, 0.0726], "si": [0.0511, 0.8939, -0.0212], "psis": [0.0433, 0.9125, -0.0682], "asis": [0.1179, 0.9117, 0.0676], "vC1": [0.0, 1.48, 0.0068], "vC2": [0.0, 1.4682, 0.0046], "vC3": [0.0, 1.4495, 0.0036], "vC4": [0.0, 1.4353, 0.0035], "vC5": [0.0, 1.4199, 0.0028], "vC6": [0.0, 1.4048, 0.0006], "vC7": [0.0, 1.3926, -0.0054], "vS2": [0.0, 0.8941, -0.0256], "spS2": [0.0, 0.8941, -0.062]};
(function () {
  const X = [1, 0, 0], Y = [0, 1, 0], Z = [0, 0, 1];
  const ARM = ['humerus', 'ulna', 'radius', 'hand'], FORE = ['ulna', 'radius', 'hand'], GIRDLE = ['clavicle', 'scapula', 'humerus', 'ulna', 'radius', 'hand'];
  const LEG = ['femur', 'patella', 'tibia', 'fibula', 'talus', 'foot'], SHANK = ['patella', 'tibia', 'fibula', 'talus', 'foot'];
  const set = (o, keys, M) => { keys.forEach((k) => { o[k] = M; }); return o; };
  const NECK = ['C7', 'C6', 'C5', 'C4', 'C3', 'C2', 'C1'];
  function neckChain(J, R, axis, total, frac) {
    const o = {}; let M = R.mul();
    NECK.forEach((v) => { M = R.mul(M, R.rot(J['v' + v], axis, total * frac[v])); o[v] = M; });
    o.skull = M; return o;
  }
  // 肩肱節律：外展時肩胛上旋（約 2：1）
  function girdleUp(J, R, deg) { const clav = R.rot(J.sc, Z, deg * 0.3); const scap = R.mul(clav, R.rot(J.scapC, Z, deg * 0.7)); return { clav, scap }; }
  // 骨盆：無名骨變換＋同側下肢跟著髖臼平移
  function pelvis(J, R, a, x) {
    const M = R.mul(R.rot(J.vS2, X, a), R.rot(J.si, Y, -x));
    const o = { hip: M }; set(o, LEG, R.tr(R.moved(M, J.hip))); return o;
  }
  window.MOTION_POSES = { pelvis };
  window.MOTIONS = [
    // ---------- 肩胛胸廓關節 ST ----------
    { id: 'st_elev', group: '肩胛胸廓關節（ST）', name: '肩胛上提（聳肩）', max: '約 12°（繞胸鎖關節）', view: { at: 'acromion', dir: [0.2, 0.15, 1], dist: 0.9 },
      movers: ['trap_u', 'levator', 'rhomboid'], antag: ['trap_l', 'pec_minor'], kb: ['k-st-nerves', 'k-shoulder-joints'],
      note: '筆記：上提＝上斜方（副神經）、提肩胛（肩胛背神經）、菱形肌協同。鎖骨向上時，胸鎖關節面向下滑動。',
      pose: (t, J, R) => set({}, GIRDLE, R.rot(J.sc, Z, 12 * t)) },
    { id: 'st_dep', group: '肩胛胸廓關節（ST）', name: '肩胛下壓', max: '約 6°', view: { at: 'acromion', dir: [0.2, 0.15, 1], dist: 0.9 },
      movers: ['trap_l', 'lat', 'pec_minor'], antag: ['trap_u', 'levator'], kb: ['k-st-nerves'],
      note: '筆記：下壓＝下斜方、闊背、鎖骨下肌、胸小肌。',
      pose: (t, J, R) => set({}, GIRDLE, R.rot(J.sc, Z, -6 * t)) },
    { id: 'st_prot', group: '肩胛胸廓關節（ST）', name: '肩胛前突（外展）', max: '約 15°', view: { at: 'scapC', dir: [0.3, 0.9, 0.2], dist: 1.0 },
      movers: ['serratus', 'pec_minor'], antag: ['rhomboid', 'trap_m'], kb: ['k-st-nerves', 'k-scap6'],
      note: '筆記：前突＝前鋸肌（長胸神經）、胸小肌。前鋸肌無力 → 翼狀肩胛。前突時胸鎖關節面與鎖骨同向滑動。',
      pose: (t, J, R) => set({}, GIRDLE, R.rot(J.sc, Y, -15 * t)) },
    { id: 'st_ret', group: '肩胛胸廓關節（ST）', name: '肩胛後縮（內收）', max: '約 10°', view: { at: 'scapC', dir: [0.2, 0.9, -0.3], dist: 1.0 },
      movers: ['trap_m', 'rhomboid', 'trap_u'], antag: ['serratus', 'pec_minor'], kb: ['k-st-nerves'],
      note: '筆記：後縮＝中斜方、菱形肌（上斜方）。後縮問題不易發現，大部分其實是前鋸肌無力。',
      pose: (t, J, R) => set({}, GIRDLE, R.rot(J.sc, Y, 10 * t)) },
    { id: 'st_up', group: '肩胛胸廓關節（ST）', name: '肩胛向上旋轉', max: '約 30°', view: { at: 'scapC', dir: [0.15, 0.1, -1], dist: 1.0 },
      movers: ['trap_u', 'trap_l', 'serratus'], antag: ['rhomboid', 'pec_minor', 'levator'], kb: ['k-st-nerves'],
      note: '筆記：向上旋轉＝上斜方、下斜方、前鋸肌。手臂外展超過 90° 一定要肩胛上旋配合。',
      pose: (t, J, R) => { const c = R.rot(J.sc, Z, 8 * t); const s = R.mul(c, R.rot(J.scapC, Z, 24 * t)); const o = { clavicle: c }; return set(o, ['scapula'].concat(ARM), s); } },
    { id: 'st_down', group: '肩胛胸廓關節（ST）', name: '肩胛向下旋轉', max: '約 12°', view: { at: 'scapC', dir: [0.15, 0.1, -1], dist: 1.0 },
      movers: ['rhomboid', 'pec_minor', 'levator'], antag: ['trap_u', 'serratus'], kb: ['k-st-nerves'],
      note: '筆記：向下旋轉＝菱形肌、胸小肌（提肩胛肌）。',
      pose: (t, J, R) => set({}, ['scapula'].concat(ARM), R.rot(J.scapC, Z, -12 * t)) },
    // ---------- 盂肱關節 GH ----------
    { id: 'gh_flex', group: '盂肱關節（GH）', name: '肩屈曲（前舉）', max: '約 150°（含肩胛上旋）', view: { at: 'shoulder', dir: [1, 0.2, 0.25], dist: 1.4 },
      movers: ['deltoid', 'biceps', 'pec_major'], antag: ['lat', 'teres_major', 'triceps'], kb: ['k-gh'],
      note: '筆記：前三角肌（腋神經）、肱二頭肌（肌皮）、喙肱肌（肌皮）、胸大肌鎖骨頭。屈曲時肱骨頭向後滑動。',
      pose: (t, J, R) => { const g = girdleUp(J, R, 30 * t); const o = { clavicle: g.clav, scapula: g.scap }; return set(o, ARM, R.mul(g.scap, R.rot(J.shoulder, X, -120 * t))); } },
    { id: 'gh_ext', group: '盂肱關節（GH）', name: '肩伸直（後伸）', max: '約 45°', view: { at: 'shoulder', dir: [1, 0.2, -0.2], dist: 1.3 },
      movers: ['deltoid', 'triceps', 'lat', 'teres_major'], antag: ['pec_major', 'biceps'], kb: ['k-gh'],
      note: '筆記：後三角肌（腋）、肱三頭肌長頭（橈）、闊背肌（胸背）、大圓肌（肩胛下）。伸直時肱骨頭向前滑動。',
      pose: (t, J, R) => set({}, ARM, R.rot(J.shoulder, X, 45 * t)) },
    { id: 'gh_abd', group: '盂肱關節（GH）', name: '肩外展（肩肱節律）', max: '約 150°（盂肱 100°＋肩胛 50°）', view: { at: 'shoulder', dir: [0.15, 0.15, 1], dist: 1.4 },
      movers: ['deltoid', 'supraspinatus', 'trap_u', 'serratus'], antag: ['lat', 'pec_major', 'teres_major'], kb: ['k-gh', 'k-shoulder-complex'],
      note: '筆記：中三角肌（腋）、棘上肌（肩胛上）。外展時肱骨頭向下滑動。「只要肱骨有動，鎖骨與肩胛一定連動」——動畫中肩胛跟著上旋。肩夾擠：初期三角肌、中期棘上肌、深層肩鎖相對位置。',
      pose: (t, J, R) => { const g = girdleUp(J, R, 50 * t); const o = { clavicle: g.clav, scapula: g.scap }; return set(o, ARM, R.mul(g.scap, R.rot(J.shoulder, Z, 100 * t))); } },
    { id: 'gh_add', group: '盂肱關節（GH）', name: '肩內收（由外展收回）', max: '90° → 0°', view: { at: 'shoulder', dir: [0.15, 0.15, 1], dist: 1.4 },
      movers: ['lat', 'pec_major', 'teres_major'], antag: ['deltoid', 'supraspinatus'], kb: ['k-gh'],
      note: '筆記：喙肱肌（肌皮）、胸大肌（胸）、闊背肌（胸背）、大圓肌。內收時肱骨頭向上滑動。',
      pose: (t, J, R) => set({}, ARM, R.rot(J.shoulder, Z, 90 * (1 - t))) },
    { id: 'gh_hadd', group: '盂肱關節（GH）', name: '肩水平內收', max: '外展 90° 起，向前約 120°', view: { at: 'shoulder', dir: [0.3, 1, 0.5], dist: 1.4 },
      movers: ['pec_major', 'deltoid'], antag: ['deltoid', 'rhomboid', 'trap_m'], kb: ['k-gh'],
      note: '水平內收時肱骨頭向後滑動；水平外展時向前滑動（筆記）。',
      pose: (t, J, R) => set({}, ARM, R.mul(R.rot(J.shoulder, Y, -115 * t), R.rot(J.shoulder, Z, 90))) },
    { id: 'gh_er', group: '盂肱關節（GH）', name: '肩外轉（屈肘 90°）', max: '約 60°', view: { at: 'shoulder', dir: [0.5, 1, 0.6], dist: 1.2 },
      movers: ['infraspinatus', 'teres_minor', 'deltoid'], antag: ['subscap', 'pec_major', 'lat', 'teres_major'], kb: ['k-gh', 'k-cuff'],
      note: '筆記：棘下肌（肩胛上）、小圓肌（腋）、後三角肌。外轉時肱骨頭向前滑動。大結節連外轉肌。',
      pose: (t, J, R) => { const ax = R.axis(J.elbow, J.shoulder); const H = R.rot(J.shoulder, ax, 60 * t); const o = { humerus: H }; return set(o, FORE, R.mul(H, R.rot(J.elbow, R.axis(J.medEpi, J.latEpi), -90))); } },
    { id: 'gh_ir', group: '盂肱關節（GH）', name: '肩內轉（屈肘 90°）', max: '約 70°', view: { at: 'shoulder', dir: [0.5, 1, 0.6], dist: 1.2 },
      movers: ['subscap', 'pec_major', 'lat', 'teres_major', 'deltoid'], antag: ['infraspinatus', 'teres_minor'], kb: ['k-gh'],
      note: '筆記：肩胛下肌（肩胛下）、闊背肌（胸背）、大圓肌、胸大肌（胸）、前三角肌。內轉時肱骨頭向後滑動。小結節連內轉肌。',
      pose: (t, J, R) => { const ax = R.axis(J.elbow, J.shoulder); const H = R.rot(J.shoulder, ax, -70 * t); const o = { humerus: H }; return set(o, FORE, R.mul(H, R.rot(J.elbow, R.axis(J.medEpi, J.latEpi), -90))); } },
    // ---------- 肘 ----------
    { id: 'el_flex', group: '肘與前臂', name: '屈肘', max: '約 140°', view: { at: 'elbow', dir: [1, 0.2, 0.3], dist: 1.0 },
      movers: ['biceps', 'brachialis', 'brachiorad'], antag: ['triceps'], kb: ['k-elbow'],
      note: '肱肌在前臂旋前或旋後都能屈肘；肱二頭肌同時旋後；肱橈肌在半旋前位最有力。',
      pose: (t, J, R) => set({}, FORE, R.rot(J.elbow, R.axis(J.medEpi, J.latEpi), -140 * t)) },
    { id: 'el_pro', group: '肘與前臂', name: '前臂旋前', max: '約 80°', view: { at: 'wrist', dir: [0.4, 0.3, 1], dist: 0.8 },
      movers: ['pronator', 'forearm_flex', 'brachiorad'], antag: ['supinator', 'biceps'], kb: ['k-elbow'],
      note: '筆記：旋前主要＝旋前圓肌、旋前方肌；次要＝橈側屈腕肌、掌長肌、肱橈肌 → 屈腕肌群 → 肱骨內上髁（高爾夫球肘）。尺骨不動，橈骨繞著尺骨轉。',
      pose: (t, J, R) => set({}, ['radius', 'hand'], R.rot(J.radHead, R.axis(J.ulnHead, J.radHead), -80 * t)) },
    { id: 'el_sup', group: '肘與前臂', name: '前臂旋後', max: '旋前 80° → 0°', view: { at: 'wrist', dir: [0.4, 0.3, 1], dist: 0.8 },
      movers: ['supinator', 'biceps', 'forearm_ext', 'brachiorad'], antag: ['pronator'], kb: ['k-elbow'],
      note: '筆記：旋後主要＝旋後肌、肱二頭肌；次要＝橈側伸腕肌、伸拇長肌、伸食指肌、肱橈肌 → 伸肌群 → 肱骨外上髁（網球肘）。橈神經穿過旋後肌。',
      pose: (t, J, R) => set({}, ['radius', 'hand'], R.rot(J.radHead, R.axis(J.ulnHead, J.radHead), -80 * (1 - t))) },
    // ---------- 髖 ----------
    { id: 'hip_flex', group: '髖關節', name: '髖屈曲（抬膝）', max: '髖 100°＋膝 100°', view: { at: 'hip', dir: [1, 0.15, 0.3], dist: 1.6 },
      movers: ['iliopsoas', 'rectus_fem', 'sartorius', 'tfl_itb'], antag: ['glute_max', 'hamstrings'], kb: ['k-angle1'],
      note: '髂腰肌是最主要的屈髖肌；股直肌是股四頭肌中唯一跨過髖關節的一條。',
      pose: (t, J, R) => { const T = R.rot(J.hip, X, -100 * t); const o = { femur: T }; return set(o, SHANK, R.mul(T, R.rot(J.knee, X, 100 * t))); } },
    { id: 'hip_ext', group: '髖關節', name: '髖伸直（後伸）', max: '約 25°', view: { at: 'hip', dir: [1, 0.15, -0.2], dist: 1.6 },
      movers: ['glute_max', 'hamstrings'], antag: ['iliopsoas', 'rectus_fem'], kb: ['k-angle1'],
      note: '臀大肌與膕繩肌伸髖；髂腰肌、股直肌被拉長。',
      pose: (t, J, R) => set({}, LEG, R.rot(J.hip, X, 25 * t)) },
    { id: 'hip_abd', group: '髖關節', name: '髖外展', max: '約 40°', view: { at: 'hip', dir: [0.1, 0.1, 1], dist: 1.6 },
      movers: ['glute_med', 'glute_min', 'tfl_itb'], antag: ['adductors'], kb: ['k-angle2', 'k-hip-rot'],
      note: '臀中肌是單腳站時穩定骨盆的關鍵（無力 → 對側骨盆下掉）。',
      pose: (t, J, R) => set({}, LEG, R.rot(J.hip, Z, 40 * t)) },
    { id: 'hip_add', group: '髖關節', name: '髖內收', max: '約 25°（稍前屈避開對側腿）', view: { at: 'hip', dir: [0.1, 0.1, 1], dist: 1.6 },
      movers: ['adductors'], antag: ['glute_med', 'glute_min', 'tfl_itb'], kb: ['k-angle3'],
      note: '內收肌群＝內收大、長、短肌、恥骨肌、股薄肌（筆記：③ IN 的處理對象）。',
      pose: (t, J, R) => set({}, LEG, R.mul(R.rot(J.hip, X, -15 * t), R.rot(J.hip, Z, -25 * t))) },
    { id: 'hip_er', group: '髖關節', name: '髖外轉', max: '約 45°', view: { at: 'knee', dir: [0.3, 0.8, 0.6], dist: 1.6 },
      movers: ['deep_rot', 'piriformis', 'glute_max'], antag: ['glute_med', 'glute_min', 'tfl_itb'], kb: ['k-hip-rot', 'k-angle2'],
      note: '臀後六肌（梨狀肌、閉孔內外肌、上下孖肌、股方肌）位在股骨旋轉軸後方。腳尖朝外。',
      pose: (t, J, R) => set({}, LEG, R.rot(J.hip, R.axis(J.ankle, J.hip), 45 * t)) },
    { id: 'hip_ir', group: '髖關節', name: '髖內轉', max: '約 35°', view: { at: 'knee', dir: [0.3, 0.8, 0.6], dist: 1.6 },
      movers: ['glute_med', 'glute_min', 'tfl_itb'], antag: ['deep_rot', 'piriformis'], kb: ['k-hip-rot'],
      note: '臀中肌前束、臀小肌、闊筋膜張肌位在旋轉軸前方。腳尖朝內。',
      pose: (t, J, R) => set({}, LEG, R.rot(J.hip, R.axis(J.ankle, J.hip), -35 * t)) },
    // ---------- 膝 ----------
    { id: 'knee_flex', group: '膝關節', name: '屈膝', max: '約 120°', view: { at: 'knee', dir: [1, 0.2, 0.1], dist: 1.3 },
      movers: ['hamstrings', 'gastroc', 'popliteus', 'sartorius'], antag: ['rectus_fem', 'vastus_lat', 'vastus_med', 'vastus_int'], kb: ['k-knee-more', 'k-popliteus'],
      note: '膕肌在屈膝初期讓脛骨內旋（解鎖）；膝伸直最後 30° 脛骨外轉約 10°。',
      pose: (t, J, R) => set({}, SHANK, R.rot(J.knee, R.axis(J.femMed, J.femLat), 120 * t)) },
    { id: 'knee_ext', group: '膝關節', name: '伸膝', max: '90° → 0°', view: { at: 'knee', dir: [1, 0.2, 0.1], dist: 1.3 },
      movers: ['rectus_fem', 'vastus_lat', 'vastus_med', 'vastus_int'], antag: ['hamstrings', 'gastroc'], kb: ['k-knee-more', 'k-quads'],
      note: '股四頭肌經髕骨、髕韌帶止於脛骨粗隆；髕骨是人體最大的種子骨。',
      pose: (t, J, R) => set({}, SHANK, R.rot(J.knee, R.axis(J.femMed, J.femLat), 90 * (1 - t))) },
    // ---------- 踝 ----------
    { id: 'ank_df', group: '踝與足', name: '踝背屈', max: '約 20°', view: { at: 'ankle', dir: [1, 0.3, 0.2], dist: 0.8 },
      movers: ['tib_ant', 'toe_ext'], antag: ['gastroc', 'soleus'], kb: ['k-ankle-lig'],
      note: '筆記：背屈＝脛前肌。蹲下腳跟離地 → 背屈受限，膝會用旋轉代償。',
      pose: (t, J, R) => set({}, ['talus', 'foot'], R.rot(J.talus, R.axis(J.medMall, J.latMall), -20 * t)) },
    { id: 'ank_pf', group: '踝與足', name: '踝蹠屈', max: '約 40°', view: { at: 'ankle', dir: [1, 0.3, 0.2], dist: 0.8 },
      movers: ['gastroc', 'soleus', 'tib_post', 'peroneus'], antag: ['tib_ant', 'toe_ext'], kb: ['k-ankle-lig'],
      note: '筆記：蹠屈＝腓腸肌、比目魚肌。',
      pose: (t, J, R) => set({}, ['talus', 'foot'], R.rot(J.talus, R.axis(J.medMall, J.latMall), 40 * t)) },
    { id: 'ank_inv', group: '踝與足', name: '足內翻', max: '約 25°', view: { at: 'ankle', dir: [0.2, 0.3, 1], dist: 0.8 },
      movers: ['tib_post', 'tib_ant'], antag: ['peroneus'], kb: ['k-ankle-lig', 'k-limb-rot'],
      note: '筆記：內翻＝脛後肌（肝經）。距骨不動，跟骨以下翻轉（距下關節）。',
      pose: (t, J, R) => set({}, ['foot'], R.rot(J.talus, R.axis(J.calc, R.mid(J.mt1, J.mt5)), -25 * t)) },
    { id: 'ank_ev', group: '踝與足', name: '足外翻', max: '約 15°', view: { at: 'ankle', dir: [0.2, 0.3, 1], dist: 0.8 },
      movers: ['peroneus'], antag: ['tib_post', 'tib_ant'], kb: ['k-ankle-lig'],
      note: '筆記：外翻＝腓骨長、短肌。舊扭傷常是內翻扭傷，腓骨肌與外踝韌帶受傷。',
      pose: (t, J, R) => set({}, ['foot'], R.rot(J.talus, R.axis(J.calc, R.mid(J.mt1, J.mt5)), 15 * t)) },
    // ---------- 骨盆三個角度 ----------
    { id: 'pel_A', group: '骨盆三個角度（示意放大）', name: '① A 前傾', max: '示意約 10°', pelvis: true, view: { at: 'psis', dir: [1, 0.35, -0.35], dist: 1.1 },
      movers: ['iliopsoas', 'rectus_fem'], antag: ['hamstrings', 'glute_max'], kb: ['k-angle1'],
      note: '無名骨繞 S2 橫軸往前轉：髂後上棘比 S2 高、坐骨結節變高；髖臼往下後 → A 側長腳（筆記）。主角：股直肌、髂肌、腰大肌。',
      pose: (t, J, R) => pelvis(J, R, 10 * t, 0) },
    { id: 'pel_P', group: '骨盆三個角度（示意放大）', name: '① P 後傾', max: '示意約 10°', pelvis: true, view: { at: 'psis', dir: [1, 0.35, -0.35], dist: 1.1 },
      movers: ['hamstrings'], antag: ['iliopsoas', 'rectus_fem'], kb: ['k-angle1'],
      note: '髂後上棘變低、坐骨低、臀部下垂、短腿（筆記）。主角：附著在坐骨結節的半腱肌、半膜肌、股二頭肌長頭。',
      pose: (t, J, R) => pelvis(J, R, -10 * t, 0) },
    { id: 'pel_EX', group: '骨盆三個角度（示意放大）', name: '② EX 外轉', max: '示意約 8°', pelvis: true, view: { at: 'spS2', dir: [0, 0.6, -1], dist: 0.9 },
      movers: ['glute_med', 'glute_min', 'tfl_itb'], antag: ['deep_rot', 'piriformis'], kb: ['k-angle2'],
      note: '髂後上棘同高、離 S2 變遠（繞薦髂關節的垂直軸）；脊椎逆向旋轉。筆記：② EX 處理臀中、臀小、闊筋膜張肌。',
      pose: (t, J, R) => pelvis(J, R, 0, 8 * t) },
    { id: 'pel_IN', group: '骨盆三個角度（示意放大）', name: '② IN 內轉', max: '示意約 8°', pelvis: true, view: { at: 'spS2', dir: [0, 0.6, -1], dist: 0.9 },
      movers: ['deep_rot', 'piriformis'], antag: ['glute_med', 'tfl_itb'], kb: ['k-angle2'],
      note: '髂後上棘同高、靠近 S2。筆記：② IN 處理臀後六肌。',
      pose: (t, J, R) => pelvis(J, R, 0, -8 * t) },
    { id: 'pel_3EX', group: '骨盆三個角度（示意放大）', name: '③ EX 耳狀面外展', max: '示意 A 8°＋EX 6°', pelvis: true, view: { at: 'spS2', dir: [0.6, 0.6, -1], dist: 1.0 },
      movers: ['glute_med', 'glute_min', 'tfl_itb'], antag: ['adductors'], kb: ['k-angle3'],
      note: '沿耳狀面外展：髂後上棘「又高又遠」＝第一角度 A＋第二角度 EX；脊椎同側側彎。筆記：肌肉同 ② EX，做法不同。',
      pose: (t, J, R) => pelvis(J, R, 8 * t, 6 * t) },
    { id: 'pel_3IN', group: '骨盆三個角度（示意放大）', name: '③ IN 耳狀面內收', max: '示意 P 8°＋IN 6°', pelvis: true, view: { at: 'spS2', dir: [0.6, 0.6, -1], dist: 1.0 },
      movers: ['adductors'], antag: ['glute_med', 'tfl_itb'], kb: ['k-angle3'],
      note: '髂後上棘「又低又近」＝第一角度 P＋第二角度 IN。筆記：③ IN 處理內收長短肌、股薄肌、恥骨肌（內收肌群）。',
      pose: (t, J, R) => pelvis(J, R, -8 * t, -6 * t) },
    // ---------- 頸椎 ----------
    { id: 'neck_rot', group: '頸椎', name: '頸旋轉（轉向此側）', max: '約 70°，C1–C2 佔一半', view: { at: 'vC2', dir: [0.3, 0.4, 1], dist: 0.8 },
      movers: [['scm', 'opp'], 'splenius', 'subocc'], antag: ['scm', ['splenius', 'opp']], kb: ['k-facets', 'k-cervical'],
      note: '轉頭向左＝右側胸鎖乳突肌＋左側頭夾肌。筆記（Fryette）：上頸椎側彎與旋轉反向，C2 以下同向；頸椎小面關節 45°，主要貢獻旋轉。',
      pose: (t, J, R) => neckChain(J, R, Y, 70 * t, { C7: 0.03, C6: 0.05, C5: 0.07, C4: 0.08, C3: 0.09, C2: 0.1, C1: 0.58 }) },
    { id: 'neck_lat', group: '頸椎', name: '頸側彎（向此側）', max: '約 40°', view: { at: 'vC4', dir: [0, 0.2, 1], dist: 0.8 },
      movers: ['scalene', 'scm', 'levator', 'trap_u'], antag: [['scalene', 'opp'], ['trap_u', 'opp'], ['levator', 'opp']], kb: ['k-facets'],
      note: '同側斜角肌、胸鎖乳突肌、提肩胛、上斜方收縮；對側被拉長。',
      pose: (t, J, R) => neckChain(J, R, Z, -40 * t, { C7: 0.14, C6: 0.15, C5: 0.15, C4: 0.15, C3: 0.15, C2: 0.14, C1: 0.12 }) },
    { id: 'neck_flex', group: '頸椎', name: '頸屈曲（低頭）', max: '約 45°', side: false, view: { at: 'vC4', dir: [1, 0.2, 0.1], dist: 0.8 },
      movers: ['scm', 'scalene'], antag: ['splenius', 'subocc', 'trap_u'], kb: ['k-scm-lever'],
      note: '兩側胸鎖乳突肌、斜角肌；後側頭夾肌、枕下肌群被拉長。',
      pose: (t, J, R) => neckChain(J, R, X, 45 * t, { C7: 0.16, C6: 0.16, C5: 0.16, C4: 0.15, C3: 0.13, C2: 0.1, C1: 0.14 }) },
    { id: 'neck_ext', group: '頸椎', name: '頸伸直（抬頭）', max: '約 45°', side: false, view: { at: 'vC4', dir: [1, 0.2, 0.1], dist: 0.8 },
      movers: ['splenius', 'subocc', 'trap_u', 'erector'], antag: ['scm'], kb: ['k-cervical'],
      note: '頭前傾時上頸過伸、枕下肌群縮短（後頭痛、頭暈）。',
      pose: (t, J, R) => neckChain(J, R, X, -45 * t, { C7: 0.12, C6: 0.13, C5: 0.14, C4: 0.14, C3: 0.14, C2: 0.13, C1: 0.2 }) },
  ];
})();
