/* 肌肉資料：起止點、作用、觸診、放鬆手法、轉移痛、相關穴位/經筋，以及 3D 纖維走向
   fibers 規格見 body3d.js 的 P()；x 以左側定義，自動鏡像到右側 */
window.MUSCLES = [
  // ===== 頸 =====
  { id: 'scm', name: '胸鎖乳突肌', en: 'Sternocleidomastoid', region: '頸', layer: '淺層', r: 0.0065, inset: 0.004,
    origin: '胸骨柄前面（胸骨頭）、鎖骨內側 1/3（鎖骨頭）', insertion: '顳骨乳突、上項線外側',
    action: '單側收縮：頭向同側側彎、臉轉向對側；雙側：頸屈曲、頭前移；輔助吸氣',
    palpation: '客人仰臥，頭轉向對側並微抬，頸前斜行條索即是；以拇指與食指「拿」起整條肌腹，從乳突捏到胸骨。',
    release: '仰臥，頭微轉向對側。拿捏法沿肌腹由上而下分段捏揉；勿深壓頸動脈（位於其內側深層）。可配合頭向同側側彎、對側轉的伸展。',
    referral: '額頭、眼眶周圍、耳後、頭頂痛，頭暈、耳鳴感', symptoms: ['頭痛', '頭前傾', '落枕', '頭暈'],
    points: ['LI18', 'SI16', 'SI17', 'TE17'], sinew: ['SI', 'ST'],
    fibers: [{ o: [['X', 0.010, 1.412, 0.094], ['X', 0.040, 1.430, 0.082]], v: [[['X', 0.036, 1.468, 0.045], ['X', 0.050, 1.468, 0.032]]], i: [['LM', 'mastoid'], ['OFF', ['LM', 'mastoid'], -0.004, 0.006, -0.012]], n: 4 }] },
  { id: 'scalene', name: '斜角肌（前中後）', en: 'Scalenes', region: '頸', layer: '中層', r: 0.0045, deep: true,
    origin: 'C2–C7 橫突', insertion: '第 1 肋（前、中斜角肌）、第 2 肋（後斜角肌）',
    action: '上提第 1、2 肋（吸氣輔助）；單側：頸側彎；雙側：頸屈曲',
    palpation: '胸鎖乳突肌鎖骨頭後外側、鎖骨上窩（缺盆）上方，客人用力吸氣時可感到收縮。',
    release: '輕柔指腹揉法、點按，避免強力按壓鎖骨上窩（臂神經叢、鎖骨下動脈）。伸展：頭向對側側彎並微後仰。',
    referral: '胸前、肩胛內緣、上臂外側至拇指食指，常被誤認為手麻', symptoms: ['手麻', '胸廓出口症候群', '頸痛', '呼吸淺'],
    points: ['ST12', 'LI17'], sinew: ['LI'],
    fibers: [{ o: [['TP', 'C3', 0.026], ['TP', 'C6', 0.030]], i: [['RIB', 1, 0.45, 0.0], ['RIB', 1, 0.62, 0.0]], n: 3 }] },
  { id: 'trap_u', name: '斜方肌（上束）', en: 'Upper trapezius', region: '頸肩', layer: '淺層', r: 0.0075, inset: 0.006,
    origin: '枕外隆凸、上項線內 1/3、項韌帶（C1–C7）', insertion: '鎖骨外側 1/3 後緣、肩峰',
    action: '上提肩胛骨、肩胛骨上迴旋；單側使頭向同側側彎、轉向對側',
    palpation: '肩井一帶的肩上肌肉，用拇指與四指「拿」起即是。坐姿聳肩可感覺收縮。',
    release: '拿法拿肩井、滾法沿頸根到肩峰、點按肩井與風池。伸展：頭向對側側彎、對側手輕帶。常與提肩胛肌一起處理。',
    referral: '同側頸後到耳後、太陽穴（緊張型頭痛的典型來源）', symptoms: ['肩頸僵硬', '高低肩', '頭痛', '落枕'],
    points: ['GB21', 'GB20', 'BL10', 'SI15', 'TE15'], sinew: ['BL', 'SI', 'GB'],
    fibers: [{ o: [['LM', 'EOP'], ['SP', 'C3'], ['SP', 'C6'], ['SP', 'C7']], v: [[['X', 0.040, 1.520, -0.062], ['X', 0.055, 1.478, -0.050], ['X', 0.090, 1.458, -0.050], ['X', 0.110, 1.452, -0.055]]], i: [['MIX', ['LM', 'clavMid'], ['LM', 'acromion'], 0.45], ['LM', 'acromion']], n: 6 }] },
  { id: 'trap_m', name: '斜方肌（中束）', en: 'Middle trapezius', region: '背', layer: '淺層', r: 0.007, inset: 0.006,
    origin: 'C7–T5 棘突', insertion: '肩峰內緣、肩胛棘上緣',
    action: '肩胛骨內收（夾背）', palpation: '兩肩胛骨之間、肩胛棘以上的橫向纖維。俯臥夾背可感覺收縮。',
    release: '俯臥，掌根揉、滾法橫向推按，指撥肩胛內緣。圓肩者此肌多為「被拉長的痠痛」，宜放鬆胸大小肌後再加強它。',
    referral: '兩肩胛之間灼熱或痠痛', symptoms: ['圓肩', '背痛', '肩胛間痛'],
    points: ['BL13', 'BL14', 'SI14', 'SI15'], sinew: ['BL'],
    fibers: [{ o: [['SP', 'C7'], ['SP', 'T5']], i: [['LM', 'acromion'], ['MIX', ['LM', 'scapMedSpine'], ['LM', 'acromion'], 0.35]], n: 5 }] },
  { id: 'trap_l', name: '斜方肌（下束）', en: 'Lower trapezius', region: '背', layer: '淺層', r: 0.0065, inset: 0.006,
    origin: 'T6–T12 棘突', insertion: '肩胛棘內側端',
    action: '肩胛骨下壓、上迴旋（舉手過頭時穩定肩胛）', palpation: '肩胛棘內端往下斜到中下胸椎棘突的三角區。',
    release: '俯臥推法由下往上沿纖維方向推、彈撥。多半需要強化而非放鬆（聳肩族常無力）。',
    referral: '肩胛內緣、頸後', symptoms: ['聳肩', '肩夾擠'], points: ['BL17', 'BL18', 'GV9'], sinew: ['BL'],
    fibers: [{ o: [['SP', 'T6'], ['SP', 'T9'], ['SP', 'T12']], i: [['MIX', ['LM', 'scapMedSpine'], ['LM', 'acromion'], 0.12], ['LM', 'scapMedSpine']], n: 5 }] },
  { id: 'levator', name: '提肩胛肌', en: 'Levator scapulae', region: '頸肩', layer: '中層', r: 0.006, inset: 0.016,
    origin: 'C1–C4 橫突後結節', insertion: '肩胛骨上角及內緣（至肩胛棘）',
    action: '上提肩胛骨、肩胛下迴旋；頸同側側彎與旋轉',
    palpation: '肩胛骨上角內上方，斜方肌深層；客人頭轉向對側時，在上角處可摸到緊硬的條索與壓痛點。',
    release: '點按、彈撥肩胛上角附著點（常是痛點／阿是穴），配合頭向對側轉、低頭的伸展。落枕時「頭轉不過去」常與它有關。',
    referral: '頸肩交界、肩胛內緣', symptoms: ['落枕', '頸不能轉', '肩胛上角痛', '高低肩'],
    points: ['SI14', 'SI15', 'GB21'], sinew: ['SI', 'TE'],
    fibers: [{ o: [['TP', 'C1', 0.034], ['TP', 'C4', 0.028]], v: [[['X', 0.058, 1.47, -0.035], ['X', 0.062, 1.45, -0.04]]], i: [['LM', 'scapSup'], ['MIX', ['LM', 'scapSup'], ['LM', 'scapMedSpine'], 0.6]], n: 3 }] },
  { id: 'splenius', name: '頭夾肌／頸夾肌', en: 'Splenius capitis / cervicis', region: '頸', layer: '中層', r: 0.006, inset: 0.012,
    origin: '項韌帶下半、C7–T4 棘突', insertion: '乳突、上項線外側（頭夾肌）；C1–C3 橫突（頸夾肌）',
    action: '頭頸伸直；單側使頭轉向同側', palpation: '頸後斜方肌深層、由下內往上外斜行，乳突下方內側最好摸。',
    release: '拇指沿風池—天柱往下彈撥、揉；頭微低並轉向對側伸展。',
    referral: '頭頂、眼後、枕部', symptoms: ['頭痛', '頸僵'], points: ['GB20', 'BL10', 'GB12'], sinew: ['BL'],
    fibers: [{ o: [['SP', 'C5'], ['SP', 'T3']], i: [['LM', 'mastoid'], ['LM', 'occLine']], n: 4 }] },
  { id: 'subocc', name: '枕下肌群', en: 'Suboccipitals', region: '頸', layer: '深層', r: 0.0045, deep: true,
    origin: 'C1 後弓與橫突、C2 棘突', insertion: '枕骨下項線、C1 橫突',
    action: '頭部細微的點頭、後仰與旋轉（C0–C1–C2 的姿勢控制）',
    palpation: '枕骨下緣與 C2 棘突之間的凹陷深層（風池、天柱一帶往深處）。',
    release: '仰臥，雙手指腹勾住枕骨下緣，利用頭部重量做持續壓放（枕下放鬆），1–2 分鐘。頭前傾者幾乎都很緊。',
    referral: '頭兩側如帶狀、眼窩後', symptoms: ['頭痛', '頭前傾', '眼睛疲勞', '頭暈'], points: ['GB20', 'BL10', 'GV16'], sinew: ['BL', 'GB'],
    fibers: [[['SP', 'C2'], ['X', 0.012, 1.535, -0.07], ['X', 0.03, 1.542, -0.075]], [['TP', 'C1', 0.036], ['X', 0.042, 1.546, -0.07]], [['SP', 'C2'], ['X', 0.024, 1.52, -0.05], ['TP', 'C1', 0.034]], [['X', 0.006, 1.528, -0.05], ['X', 0.015, 1.545, -0.08]]] },
  { id: 'masseter', name: '咬肌', en: 'Masseter', region: '頭面', layer: '淺層', r: 0.006, deep: true,
    origin: '顴弓下緣', insertion: '下頷角與下頷枝外側', action: '上提下頷（咬合）',
    palpation: '咬緊牙齒時下頷角上方鼓起處（頰車）。', release: '指腹圓揉頰車、下關；張口狀態下輕輕向下推。',
    referral: '上下牙、耳前、眉弓', symptoms: ['顳顎關節痛', '磨牙', '頭痛', '口角歪斜'], points: ['ST6', 'ST7'], sinew: ['ST'],
    fibers: [{ o: [['X', 0.062, 1.572, 0.05], ['X', 0.066, 1.570, 0.03]], i: [['X', 0.055, 1.505, 0.045], ['X', 0.054, 1.505, 0.028]], n: 3 }] },
  { id: 'temporalis', name: '顳肌', en: 'Temporalis', region: '頭面', layer: '淺層', r: 0.0055, deep: true,
    origin: '顳窩（耳上方扇形區）', insertion: '下頷骨冠突', action: '上提並後拉下頷',
    palpation: '太陽穴到耳上方，咬牙時鼓動。', release: '指腹小圓揉太陽、率谷一帶，由前往後梳理。',
    referral: '太陽穴、上排牙、眉', symptoms: ['偏頭痛', '頭痛', '磨牙'], points: ['GB8', 'TE20', 'EX-HN5'], sinew: ['GB', 'TE'],
    fibers: [{ o: [['X', 0.064, 1.648, 0.045], ['X', 0.07, 1.66, 0.01], ['X', 0.066, 1.65, -0.03]], i: [['X', 0.06, 1.565, 0.04]], n: 5 }] },

  // ===== 肩背 =====
  { id: 'rhomboid', name: '菱形肌', en: 'Rhomboids', region: '背', layer: '中層', r: 0.0065, inset: 0.014,
    origin: 'C7–T5 棘突', insertion: '肩胛骨內緣（肩胛棘至下角）', action: '肩胛骨內收、上提、下迴旋',
    palpation: '肩胛內緣與脊椎之間，斜方肌深層，斜向下外。', release: '俯臥，手臂背到腰後讓肩胛內緣翹起，拇指沿內緣彈撥；掌根推。圓肩者多為被拉長的痛。',
    referral: '肩胛內緣', symptoms: ['肩胛間痛', '圓肩', '駝背'], points: ['BL41', 'BL42', 'BL43', 'BL15'], sinew: ['BL', 'SI'],
    fibers: [{ o: [['SP', 'C7'], ['SP', 'T5']], i: [['LM', 'scapMedSpine'], ['LM', 'scapInf']], n: 6 }] },
  { id: 'supraspinatus', name: '棘上肌', en: 'Supraspinatus', region: '肩', layer: '深層', r: 0.0055, inset: 0.016,
    origin: '肩胛骨棘上窩', insertion: '肱骨大結節上面', action: '肩外展起始 0–15°、穩定肱骨頭',
    palpation: '肩胛棘上方的凹窩（秉風）深壓；肌腱在肩峰前外下方。', release: '點按秉風、橫向彈撥大結節處肌腱（輕）。肩夾擠者先放鬆胸小肌、上斜方。',
    referral: '肩外側三角肌區，可至前臂外側', symptoms: ['肩痛', '舉手痛', '五十肩'], points: ['SI12', 'SI13', 'LI15'], sinew: ['LI', 'SI'],
    fibers: [[['X', 0.088, 1.408, -0.085], ['X', 0.15, 1.432, -0.06], ['LM', 'gTub']], [['X', 0.1, 1.398, -0.088], ['X', 0.155, 1.425, -0.055], ['LM', 'gTub']]] },
  { id: 'infraspinatus', name: '棘下肌', en: 'Infraspinatus', region: '肩', layer: '淺層', r: 0.0065, inset: 0.014,
    origin: '肩胛骨棘下窩', insertion: '肱骨大結節中面', action: '肩外旋、穩定肱骨頭',
    palpation: '肩胛骨中央（天宗）一帶，按下常有強烈痠脹並放射到肩前。', release: '拇指或肘尖點按天宗、在棘下窩做撥法；手臂內旋位伸展。',
    referral: '肩前深處、上臂前外側（常被誤以為肩前問題）', symptoms: ['肩前痛', '舉手痛', '五十肩', '睡覺壓肩痛'], points: ['SI11', 'SI10', 'SI9'], sinew: ['SI'],
    fibers: [{ o: [['X', 0.085, 1.362, -0.1], ['X', 0.09, 1.30, -0.1], ['X', 0.098, 1.265, -0.096]], v: [[['X', 0.15, 1.37, -0.082]]], i: [['OFF', ['LM', 'gTub'], 0, -0.008, -0.02]], n: 5 }] },
  { id: 'teres_minor', name: '小圓肌', en: 'Teres minor', region: '肩', layer: '中層', r: 0.0055, inset: 0.012,
    origin: '肩胛骨外緣上 2/3', insertion: '肱骨大結節下面', action: '肩外旋、內收',
    palpation: '腋後皺襞上方、肩胛外緣，肩貞穴附近。', release: '點按肩貞、臑俞；側臥撥揉外緣。', referral: '肩後三角肌後束區',
    symptoms: ['肩後痛'], points: ['SI9', 'SI10'], sinew: ['SI'],
    fibers: [[['LM', 'scapLatBorderMid'], ['X', 0.165, 1.37, -0.065], ['OFF', ['LM', 'gTub'], 0, -0.022, -0.026]]] },
  { id: 'teres_major', name: '大圓肌', en: 'Teres major', region: '肩', layer: '淺層', r: 0.0065, inset: 0.01,
    origin: '肩胛骨下角背面', insertion: '肱骨小結節嵴（結節間溝內唇）', action: '肩內旋、內收、伸展（與闊背肌同為「小幫手」）',
    palpation: '腋後皺襞下緣，靠近肩胛下角。', release: '側臥或俯臥，手臂上舉，用拿法捏腋後皺襞。', referral: '肩後、上臂後側',
    symptoms: ['舉手受限', '五十肩'], points: ['SI9'], sinew: ['SI'],
    fibers: [[['LM', 'scapInf'], ['X', 0.15, 1.30, -0.072], ['X', 0.185, 1.345, -0.035], ['OFF', ['LM', 'bicGroove'], -0.004, -0.03, 0.0]], [['OFF', ['LM', 'scapInf'], 0.012, 0.02, 0.0], ['X', 0.16, 1.31, -0.065], ['X', 0.19, 1.35, -0.03], ['OFF', ['LM', 'bicGroove'], -0.004, -0.035, 0.0]]] },
  { id: 'subscap', name: '肩胛下肌', en: 'Subscapularis', region: '肩', layer: '深層', r: 0.0065, deep: true,
    origin: '肩胛骨前面（肩胛下窩）', insertion: '肱骨小結節', action: '肩內旋、穩定肱骨頭前方',
    palpation: '仰臥手臂外展，手指從腋窩後壁往肩胛骨前面探入。', release: '在腋窩後壁輕柔點按並做手臂外旋；力道需緩。五十肩外旋受限的關鍵肌。',
    referral: '肩後、手腕背側帶狀', symptoms: ['五十肩', '外旋受限', '肩痛'], points: ['HT1'], sinew: ['HT', 'PC'],
    fibers: [[['X', 0.095, 1.36, -0.064], ['X', 0.14, 1.375, -0.04], ['LM', 'lTub']], [['X', 0.10, 1.30, -0.066], ['X', 0.145, 1.34, -0.04], ['LM', 'lTub']], [['X', 0.115, 1.27, -0.062], ['X', 0.15, 1.33, -0.035], ['OFF', ['LM', 'lTub'], 0, -0.01, 0]]] },
  { id: 'lat', name: '闊背肌', en: 'Latissimus dorsi', region: '背', layer: '淺層', r: 0.0075, inset: 0.008,
    origin: 'T7–L5 棘突、胸腰筋膜、髂嵴後部、下 3–4 肋、肩胛下角', insertion: '肱骨結節間溝底',
    action: '肩伸展、內收、內旋；雙側使骨盆前傾、腰椎伸直；單側可上提同側骨盆',
    palpation: '腋後皺襞的大塊肌肉，往下延伸到腰側。', release: '側臥，手臂上舉，滾法與掌推由腰往腋下；拿捏腋後皺襞。伸展：側臥手高舉過頭、身體側彎。',
    referral: '肩胛下角附近、上臂內側到無名指小指', symptoms: ['舉手受限', '下背痛', '骨盆前傾', '高低肩'],
    points: ['BL17', 'BL18', 'GB22'], sinew: ['BL', 'SP'],
    fibers: [{ o: [['SP', 'T7'], ['SP', 'T10'], ['SP', 'L1'], ['SP', 'L4'], ['LM', 'crestPost']], v: [[['TA', 1.30, 150, 0.008], ['TA', 1.24, 135, 0.008], ['TA', 1.17, 120, 0.008], ['TA', 1.12, 112, 0.008], ['TA', 1.08, 108, 0.008]], [['X', 0.162, 1.33, -0.05]]], i: [['LM', 'bicGroove']], n: 8 }] },
  { id: 'serratus', name: '前鋸肌', en: 'Serratus anterior', region: '胸', layer: '中層', r: 0.0055, inset: 0.012,
    origin: '第 1–8（9）肋外側面', insertion: '肩胛骨內緣前面',
    action: '肩胛骨前引、上迴旋，把肩胛貼住胸廓（翼狀肩胛為其無力）',
    palpation: '腋中線肋骨上鋸齒狀的肌肉，客人推牆時明顯。', release: '側臥，手指沿肋間由前往後撥揉；勿壓到乳房組織。',
    referral: '腋中線、肩胛下角內側、手臂內側', symptoms: ['翼狀肩胛', '側胸痛', '呼吸痛'], points: ['SP21', 'GB22'], sinew: ['SP'],
    fibers: [2, 3, 4, 5, 6, 7, 8].map((n) => [['RIB', n, 0.66, -0.004], ['TA', 1.42 - n * 0.025, 105, 0.012], ['X', 0.088, 1.40 - n * 0.019, -0.072]]) },
  { id: 'pec_major', name: '胸大肌', en: 'Pectoralis major', region: '胸', layer: '淺層', r: 0.0085, inset: 0.006,
    origin: '鎖骨內側半、胸骨、第 1–6 肋軟骨', insertion: '肱骨結節間溝外唇', action: '肩內收、內旋、屈曲',
    palpation: '腋前皺襞的大塊肌肉。', release: '仰臥，拿捏腋前皺襞；手臂外展 90° 外旋做伸展（門框伸展）。圓肩、駝背的主要緊縮肌。',
    referral: '胸前、乳房、上臂內側', symptoms: ['圓肩', '駝背', '胸悶', '肩前痛'], points: ['LU1', 'LU2', 'ST15', 'ST16', 'KI25'], sinew: ['LU', 'PC', 'HT'],
    fibers: [{ o: [['LM', 'clavMid'], ['LM', 'sternoclav'], ['X', 0.014, 1.36, 0.115], ['X', 0.016, 1.28, 0.118], ['X', 0.05, 1.245, 0.112]], v: [[['X', 0.12, 1.405, 0.07], ['X', 0.12, 1.37, 0.09], ['X', 0.12, 1.33, 0.09], ['X', 0.12, 1.29, 0.075]], [['X', 0.172, 1.37, 0.04]]], i: [['OFF', ['LM', 'bicGroove'], 0.008, -0.018, 0.0]], n: 8 }] },
  { id: 'pec_minor', name: '胸小肌', en: 'Pectoralis minor', region: '胸', layer: '深層', r: 0.0065, inset: 0.022,
    origin: '第 3–5 肋前面', insertion: '肩胛骨喙突', action: '肩胛骨前傾、下壓、前引；上提肋骨',
    palpation: '喙突內下方，胸大肌深層；客人手背壓腰時更明顯。', release: '仰臥，從腋前側把胸大肌推開，指腹點按喙突下方並緩緩揉開。過緊會壓迫腋下神經血管（胸廓出口）造成手麻。',
    referral: '胸前、上臂內側到中指', symptoms: ['圓肩', '手麻', '胸廓出口症候群', '肩夾擠'], points: ['LU1', 'ST15'], sinew: ['LU', 'PC'],
    fibers: [3, 4, 5].map((n) => [['RIB', n, 0.86, 0.0], ['X', 0.12, 1.38 - (n - 3) * 0.015, 0.08], ['LM', 'coracoid']]) },
  { id: 'deltoid', name: '三角肌', en: 'Deltoid', region: '肩', layer: '淺層', r: 0.009, inset: 0.004,
    origin: '鎖骨外 1/3（前束）、肩峰（中束）、肩胛棘（後束）', insertion: '肱骨三角肌粗隆',
    action: '前束：屈曲內旋；中束：外展；後束：伸展外旋',
    palpation: '肩部圓形隆起；肩髃（前）、肩髎（後）兩凹陷。', release: '拿揉、滾法、搓法；配合不同方向的被動活動。',
    referral: '局部三角肌區', symptoms: ['肩痛', '舉手痛'], points: ['LI15', 'TE14', 'LI14', 'SI10'], sinew: ['LI', 'TE', 'SI'],
    fibers: [{ o: [['MIX', ['LM', 'clavMid'], ['LM', 'acromion'], 0.55], ['LM', 'acromion'], ['OFF', ['LM', 'acromion'], -0.02, -0.006, -0.05], ['X', 0.12, 1.405, -0.098]], v: [[['L', 'uarm', 0.12, -35, 0.0], ['L', 'uarm', 0.12, 85, 0.0], ['L', 'uarm', 0.14, 200, 0.0]]], i: [['LM', 'deltTub']], n: 9 }] },
  // ===== 上肢 =====
  { id: 'biceps', name: '肱二頭肌', en: 'Biceps brachii', region: '上肢', layer: '淺層', r: 0.008, inset: 0.008,
    origin: '長頭：盂上結節（經結節間溝）；短頭：喙突', insertion: '橈骨粗隆、肱二頭肌腱膜', action: '屈肘、前臂旋後、輔助肩屈曲',
    palpation: '上臂前側；長頭肌腱在肩前結節間溝（肩前痛常見壓痛處）。', release: '拿捏上臂前側；結節間溝處輕柔橫撥。伸展：肩伸展、肘伸直、前臂旋前。',
    referral: '肩前、肘窩', symptoms: ['肩前痛', '肘痛'], points: ['LU3', 'LU4', 'LU5', 'PC2'], sinew: ['LU', 'PC'],
    fibers: [[['LM', 'coracoid'], ['L', 'uarm', 0.35, -12, 0.012], ['L', 'uarm', 0.75, 0, 0.01], ['LM', 'radTub']], [['LM', 'bicGroove'], ['L', 'uarm', 0.3, 18, 0.012], ['L', 'uarm', 0.75, 8, 0.01], ['LM', 'radTub']]] },
  { id: 'triceps', name: '肱三頭肌', en: 'Triceps brachii', region: '上肢', layer: '淺層', r: 0.008, inset: 0.008,
    origin: '長頭：盂下結節；外側頭、內側頭：肱骨後面', insertion: '尺骨鷹嘴', action: '伸肘；長頭輔助肩伸展與內收',
    palpation: '上臂後側。', release: '拿捏、滾法；肩上舉加屈肘伸展。', referral: '肩後、手肘外側、前臂背側', symptoms: ['肘痛', '舉手受限'],
    points: ['TE10', 'TE11', 'TE12', 'TE13'], sinew: ['TE', 'SI'],
    fibers: [[['X', 0.162, 1.385, -0.045], ['L', 'uarm', 0.4, 200, 0.008], ['L', 'uarm', 0.82, 185, 0.008], ['LM', 'olecranon']], [['L', 'uarm', 0.15, 160, 0.01], ['L', 'uarm', 0.5, 165, 0.008], ['L', 'uarm', 0.85, 175, 0.008], ['LM', 'olecranon']], [['L', 'uarm', 0.35, 225, 0.01], ['L', 'uarm', 0.7, 215, 0.008], ['LM', 'olecranon']]] },
  { id: 'brachiorad', name: '肱橈肌', en: 'Brachioradialis', region: '上肢', layer: '淺層', r: 0.006, inset: 0.006,
    origin: '肱骨外上髁上嵴', insertion: '橈骨莖突', action: '屈肘（前臂中立位時最強）',
    palpation: '前臂橈側上段，握拳立拳屈肘時隆起。', release: '拿捏、彈撥手三里一帶。', referral: '前臂橈側、虎口', symptoms: ['網球肘', '前臂痠'],
    points: ['LI10', 'LI11', 'LU6'], sinew: ['LI'],
    fibers: [[['L', 'uarm', 0.72, 95, 0.004], ['L', 'farm', 0.18, 75, 0.004], ['L', 'farm', 0.65, 70, 0.004], ['LM', 'radStyl']]] },
  { id: 'forearm_ext', name: '前臂伸肌群', en: 'Wrist & finger extensors', region: '上肢', layer: '淺層', r: 0.006, inset: 0.006,
    origin: '肱骨外上髁（總伸肌腱）', insertion: '掌骨與指骨背側', action: '伸腕、伸指、橈／尺側偏',
    palpation: '前臂背側上段，外上髁下方 2–3 指處（網球肘最痛點）。', release: '彈撥外上髁下方肌腹（非直接壓骨頭），前臂背側推法；腕屈伸展。',
    referral: '手肘外側、前臂背側到手背', symptoms: ['網球肘', '手腕痛', '滑鼠手'], points: ['LI11', 'LI10', 'TE5', 'TE4'], sinew: ['LI', 'TE'],
    fibers: [[['LM', 'latEpi'], ['L', 'farm', 0.3, 125, 0.006], ['L', 'farm', 0.75, 140, 0.005], ['HA', 0.3, 0.6, 'd']], [['LM', 'latEpi'], ['L', 'farm', 0.3, 150, 0.006], ['L', 'farm', 0.75, 170, 0.005], ['HA', 0.3, 0.0, 'd']], [['LM', 'latEpi'], ['L', 'farm', 0.3, 175, 0.006], ['L', 'farm', 0.75, 205, 0.005], ['HA', 0.3, -0.7, 'd']]] },
  { id: 'forearm_flex', name: '前臂屈肌群', en: 'Wrist & finger flexors', region: '上肢', layer: '淺層', r: 0.006, inset: 0.006,
    origin: '肱骨內上髁（總屈肌腱）', insertion: '掌骨與指骨掌側', action: '屈腕、屈指；旋前圓肌使前臂旋前',
    palpation: '前臂掌側上段，內上髁下方。', release: '推法由腕往肘、彈撥內上髁下方；腕伸展。', referral: '手肘內側、前臂掌側、手掌',
    symptoms: ['高爾夫球肘', '手腕痛', '腕隧道症候群', '手麻'], points: ['HT3', 'PC3', 'PC6', 'HT7'], sinew: ['HT', 'PC'],
    fibers: [[['LM', 'medEpi'], ['L', 'farm', 0.3, 320, 0.006], ['L', 'farm', 0.75, 335, 0.005], ['HA', 0.25, -0.5, 'p']], [['LM', 'medEpi'], ['L', 'farm', 0.3, 345, 0.006], ['L', 'farm', 0.75, 5, 0.005], ['HA', 0.25, 0.1, 'p']], [['LM', 'medEpi'], ['L', 'farm', 0.25, 20, 0.006], ['L', 'farm', 0.55, 50, 0.005]]] },
  // ===== 軀幹 =====
  { id: 'erector', name: '豎脊肌', en: 'Erector spinae', region: '背', layer: '中層', r: 0.0095, inset: 0.014,
    origin: '薦骨後面、髂嵴後部、腰椎棘突、胸腰筋膜', insertion: '肋骨角、胸頸椎橫突、乳突',
    action: '雙側：脊椎伸直、骨盆前傾；單側：同側側彎',
    palpation: '脊椎兩旁縱向隆起的兩條肌肉（膀胱經第一側線位置）。',
    release: '俯臥，掌根推、滾法沿膀胱經由上而下；拇指撥揉腰段。腰椎前凸過大／骨盆前傾者此肌縮短緊繃。',
    referral: '下背、臀部、肋下', symptoms: ['下背痛', '骨盆前傾', '腰椎前凸', '閃到腰'],
    points: ['BL23', 'BL25', 'BL18', 'BL20', 'BL13'], sinew: ['BL'],
    fibers: [0.016, 0.028, 0.042, 0.056, 0.068].map((x, k) => [['X', 0.012 + x * 0.6, 0.97, -0.095], ['SPX', 'L4', x * 0.95, 0.016], ['SPX', 'L1', x, 0.016], ['SPX', 'T10', x * 0.95, 0.016], ['SPX', 'T5', x * 0.9, 0.016], ['SPX', k > 2 ? 'T1' : 'C7', x * 0.85, 0.014]]) },
  { id: 'multifidus', name: '多裂肌', en: 'Multifidus', region: '背', layer: '深層', r: 0.0055, deep: true,
    origin: '薦骨後面、髂後上棘、各椎橫突／乳狀突', insertion: '上方 2–4 節棘突', action: '節段穩定、伸直與旋轉脊椎',
    palpation: '棘突旁一指寬的深層（華佗夾脊位置），腰薦段最厚。', release: '拇指在棘突旁垂直深壓並小幅撥動；常見單側萎縮或緊繃與薦椎扭轉同側。',
    referral: '棘突旁局部、薦骨', symptoms: ['下背痛', '腰椎不穩', '薦椎扭轉'], points: ['EX-B2', 'BL31', 'BL32'], sinew: ['BL'],
    fibers: ['L1', 'L2', 'L3', 'L4', 'L5'].map((n, i) => [['OFF', ['SP', ['L2', 'L3', 'L4', 'L5', 'S2'][i]], 0.022, -0.005, 0.012], ['OFF', ['SP', n], 0.012, 0.0, 0.006], ['OFF', ['SP', n], 0.002, 0.004, 0.0]]) },
  { id: 'ql', name: '腰方肌', en: 'Quadratus lumborum', region: '腰', layer: '深層', r: 0.0075, deep: true,
    origin: '髂嵴後部、髂腰韌帶', insertion: '第 12 肋下緣、L1–L4 橫突',
    action: '單側：腰側彎、上提同側骨盆（高低骨盆／長短腳的常見原因）；雙側：穩定腰椎、固定第 12 肋（吸氣）',
    palpation: '側臥，於第 12 肋與髂嵴之間、豎脊肌外緣往內深壓。', release: '側臥上腿垂在床後讓腰側打開，拇指或肘沿髂嵴上緣往內上方點按、撥；配合側彎伸展。',
    referral: '薦髂關節、臀外側、髖部', symptoms: ['下背痛', '高低骨盆', '長短腳', '閃到腰', '腰側痛'],
    points: ['BL52', 'BL23', 'GB25'], sinew: ['BL', 'GB'],
    fibers: [[['X', 0.06, 1.055, -0.055], ['X', 0.06, 1.12, -0.045], ['TP', 'L1', 0.04]], [['X', 0.085, 1.058, -0.05], ['X', 0.08, 1.13, -0.045], ['RIB', 12, 0.25, 0.03]], [['X', 0.105, 1.062, -0.04], ['X', 0.092, 1.13, -0.04], ['RIB', 12, 0.38, 0.03]], [['X', 0.075, 1.058, -0.052], ['TP', 'L3', 0.045], ['TP', 'L2', 0.044]]] },
  { id: 'rectus_abd', name: '腹直肌', en: 'Rectus abdominis', region: '腹', layer: '淺層', r: 0.008, inset: 0.006,
    origin: '恥骨嵴、恥骨聯合', insertion: '第 5–7 肋軟骨、劍突', action: '軀幹屈曲、骨盆後傾',
    palpation: '肚臍兩旁縱向肌肉（腎經、胃經之間）。', release: '仰臥屈膝，掌揉、指推；骨盆後傾／駝背者可能縮短。',
    referral: '下背帶狀、上腹', symptoms: ['骨盆後傾', '駝背', '腹痛'], points: ['ST25', 'KI16', 'CV12', 'CV6'], sinew: ['ST', 'KI'],
    fibers: [0.016, 0.034].map((x) => [['X', 0.012 + x * 0.3, 0.898, 0.076], ['T', 1.0, x, 'f'], ['T', 1.1, x + 0.004, 'f'], ['T', 1.2, x + 0.01, 'f'], ['X', x + 0.03, 1.27, 0.112]]) },
  { id: 'ext_oblique', name: '腹外斜肌', en: 'External oblique', region: '腹', layer: '淺層', r: 0.007, inset: 0.006,
    origin: '第 5–12 肋外面', insertion: '腹白線、髂嵴前部、腹股溝韌帶', action: '軀幹屈曲、轉向對側、側彎',
    palpation: '側腹，由外上往內下斜行（如手插口袋方向）。', release: '側臥掌揉、撥。', referral: '上腹、腹股溝', symptoms: ['腰側痛', '軀幹旋轉受限'],
    points: ['GB26', 'LR13', 'SP15'], sinew: ['ST', 'GB'],
    fibers: [{ o: [['TA', 1.30, 55, 0.006], ['TA', 1.22, 80, 0.006], ['TA', 1.15, 98, 0.006]], i: [['T', 1.17, 0.05, 'f'], ['T', 1.02, 0.06, 'f'], ['LM', 'ASIS']], n: 6 }] },
  { id: 'diaphragm', name: '橫膈膜', en: 'Diaphragm', region: '腹', layer: '深層', r: 0.005, deep: true,
    origin: '劍突後面、下 6 肋內面、L1–L3 椎體（膈腳）', insertion: '中心腱', action: '主要吸氣肌：收縮下降使胸腔擴大；與薦椎呼吸波連動',
    palpation: '仰臥屈膝，手指沿肋弓下緣往肋骨內側輕勾。', release: '吐氣時指腹沿肋弓下緣往上內勾住，吸氣時維持，反覆 3–5 次。',
    referral: '肋下、肩頂（膈神經 C3–C5）', symptoms: ['呼吸淺', '胸悶', '肋下痛'], points: ['BL17', 'CV14', 'LR14'], sinew: ['LU', 'PC'],
    fibers: [[['X', 0.11, 1.20, 0.07], ['X', 0.07, 1.27, 0.03], ['X', 0.0, 1.29, 0.0]], [['X', 0.12, 1.19, -0.02], ['X', 0.07, 1.27, -0.01], ['X', 0.0, 1.29, 0.0]], [['X', 0.012, 1.13, -0.005], ['X', 0.03, 1.22, 0.0], ['X', 0.0, 1.29, 0.0]]] },
  // ===== 骨盆／髖 =====
  { id: 'iliopsoas', name: '髂腰肌（腰大肌＋髂肌）', en: 'Iliopsoas', region: '髖', layer: '深層', r: 0.009, deep: true,
    origin: '腰大肌：T12–L5 椎體與橫突；髂肌：髂窩', insertion: '股骨小轉子',
    action: '髖屈曲；腰大肌使腰椎前凸、骨盆前傾；單側緊會使腰椎轉向／側彎',
    palpation: '仰臥屈膝，臍旁 2 寸往外 1 寸處緩慢斜向內後下壓（客人微抬腿可感覺收縮）；髂肌在髂前上棘內側往骨盆內勾。',
    release: '腹式呼吸配合緩壓，避開腹主動脈搏動處；Thomas 姿勢伸展。久坐族、骨盆前傾、站起來腰挺不直時首要處理。',
    referral: '腰部縱向、臀上、大腿前', symptoms: ['下背痛', '骨盆前傾', '腰椎前凸', '起身腰痛', '長短腳'],
    points: ['ST25', 'SP15', 'ST30', 'SP12'], sinew: ['SP', 'ST', 'KI'],
    fibers: [[['OFF', ['VB', 'T12'], 0.018, 0, 0.004], ['OFF', ['VB', 'L3'], 0.034, 0, 0.012], ['X', 0.07, 0.99, 0.04], ['X', 0.085, 0.915, 0.058], ['LM', 'lTroch']], [['OFF', ['VB', 'L2'], 0.03, 0, 0.0], ['OFF', ['VB', 'L5'], 0.045, 0, 0.018], ['X', 0.08, 0.95, 0.05], ['X', 0.09, 0.91, 0.056], ['LM', 'lTroch']], [['LM', 'iliacFossa'], ['X', 0.098, 0.955, 0.05], ['X', 0.098, 0.905, 0.05], ['LM', 'lTroch']], [['X', 0.12, 1.04, 0.0], ['X', 0.105, 0.97, 0.04], ['LM', 'lTroch']]] },
  { id: 'glute_max', name: '臀大肌', en: 'Gluteus maximus', region: '臀', layer: '淺層', r: 0.011, inset: 0.008,
    origin: '髂骨後部、薦骨與尾骨背面、胸腰筋膜、薦結節韌帶', insertion: '臀肌粗隆、髂脛束',
    action: '髖伸展、外旋；上部纖維外展；骨盆後傾', palpation: '臀部最大塊肌肉。',
    release: '俯臥，肘尖或掌根深揉、滾法；屈髖抱膝伸展。骨盆前傾者常無力（被拉長）。', referral: '薦骨、臀部、尾骨',
    symptoms: ['臀痛', '骨盆前傾', '薦髂關節痛', '坐骨神經痛'], points: ['BL54', 'GB30', 'BL36'], sinew: ['BL'],
    fibers: [{ o: [['LM', 'crestPost'], ['LM', 'PSIS'], ['SAC', 'S3', 1.3], ['SAC', 'S5', 1.3], ['X', 0.012, 0.888, -0.07]], v: [[['T', 0.99, 0.12, 'b'], ['T', 0.95, 0.11, 'b'], ['T', 0.91, 0.10, 'b'], ['T', 0.87, 0.09, 'b'], ['T', 0.84, 0.085, 'b']]], i: [['OFF', ['LM', 'gTroch'], 0.004, -0.02, -0.02], ['L', 'thigh', 0.2, 150, 0.006]], n: 8 }] },
  { id: 'glute_med', name: '臀中肌', en: 'Gluteus medius', region: '臀', layer: '中層', r: 0.0095, inset: 0.012,
    origin: '髂骨外面（前、後臀線之間）', insertion: '股骨大轉子外側面',
    action: '髖外展；單腳站立時穩定骨盆（無力→對側骨盆下掉、Trendelenburg）；前束內旋、後束外旋',
    palpation: '髂嵴下方 2–3 指、臀部外上方；側躺抬腿可感覺收縮。', release: '側臥，肘尖沿髂嵴下緣分段點按、撥；居髎、環跳一帶。',
    referral: '薦髂、臀部、大腿外側', symptoms: ['臀外側痛', '高低骨盆', '走路骨盆晃', '膝外側痛', '下背痛'],
    points: ['GB29', 'GB30', 'GB28'], sinew: ['GB'],
    fibers: [{ o: [['OFF', ['LM', 'ASIS'], 0.01, 0.01, -0.03], ['LM', 'crestTop'], ['X', 0.13, 1.05, -0.06], ['LM', 'crestPost']], v: [[['X', 0.17, 1.0, 0.0], ['X', 0.172, 0.98, -0.04], ['X', 0.15, 0.97, -0.075]]], i: [['OFF', ['LM', 'gTroch'], 0.006, 0.01, 0.0]], n: 7 }] },
  { id: 'glute_min', name: '臀小肌', en: 'Gluteus minimus', region: '臀', layer: '深層', r: 0.008, deep: true,
    origin: '髂骨外面（臀中肌深層，偏前）', insertion: '大轉子前緣', action: '髖外展、內旋',
    palpation: '髂前上棘後下方的深層。', release: '側臥深層點按；常與坐骨神經痛樣的大腿外側到小腿外側痛相關。',
    referral: '臀外側、大腿外側、小腿外側到外踝（類似坐骨神經痛）', symptoms: ['坐骨神經痛', '大腿外側痛'], points: ['GB29'], sinew: ['GB'],
    fibers: [{ o: [['X', 0.14, 1.03, 0.03], ['X', 0.15, 1.02, -0.02], ['X', 0.13, 1.0, -0.05]], i: [['OFF', ['LM', 'gTroch'], -0.004, 0.006, 0.015]], n: 4 }] },
  { id: 'piriformis', name: '梨狀肌', en: 'Piriformis', region: '臀', layer: '深層', r: 0.0075, deep: true,
    origin: '薦骨前面（S2–S4）', insertion: '股骨大轉子上緣', action: '髖外旋；髖屈曲 >60° 時變為外展；穩定薦髂關節',
    palpation: '俯臥，髂後上棘與尾骨尖連線的中點，與大轉子連一線，即肌腹走向（環跳、秩邊一帶深層）。',
    release: '肘尖沿此線深層持續壓 30–60 秒、撥；4 字伸展。坐骨神經多由其下方穿出，緊縮可壓迫坐骨神經。薦椎扭轉時同側常緊。',
    referral: '臀部、髖後、大腿後側（梨狀肌症候群）', symptoms: ['坐骨神經痛', '臀痛', '薦椎扭轉', '長短腳'], points: ['GB30', 'BL54'], sinew: ['BL', 'GB'],
    fibers: [[['X', 0.028, 0.995, -0.06], ['X', 0.075, 0.965, -0.078], ['X', 0.125, 0.93, -0.06], ['OFF', ['LM', 'gTroch'], -0.006, 0.012, -0.008]], [['X', 0.03, 0.965, -0.066], ['X', 0.075, 0.948, -0.08], ['X', 0.125, 0.922, -0.06], ['OFF', ['LM', 'gTroch'], -0.006, 0.008, -0.01]]] },
  { id: 'deep_rot', name: '臀後六肌（深層外旋肌）', en: 'Gemelli, obturators, quadratus femoris', region: '臀', layer: '深層', r: 0.006, deep: true,
    origin: '上孖肌：坐骨棘；下孖肌：坐骨結節；閉孔內肌：閉孔膜內面；閉孔外肌：閉孔膜外面；股方肌：坐骨結節外緣（梨狀肌另列）', insertion: '股骨大轉子內側面、轉子窩、轉子間嵴', action: '髖外旋；穩定股骨頭於髖臼',
    palpation: '俯臥，大轉子後緣往坐骨結節之間，梨狀肌下方一層一層橫向的肌束（環跳深層、秩邊外下）。',
    release: '筆記：② 骨盆 IN 的處理對象（梨狀肌＋閉孔內外肌、上下孖肌、股方肌）。肘尖或拇指沿大轉子後緣往內持續壓放；坐骨神經在梨狀肌下方經過，避免在坐骨大孔處重壓。',
    referral: '臀深部、髖後、大腿後上', symptoms: ['臀深部痛', '假性坐骨神經痛', '骨盆 IN'], points: ['GB30', 'BL54'], sinew: ['BL', 'GB'] },
  { id: 'brachialis', name: '肱肌', en: 'Brachialis', region: '上肢', layer: '深層', r: 0.006, deep: true,
    origin: '肱骨前面下半', insertion: '尺骨粗隆、冠突', action: '屈肘（不論前臂旋前或旋後，都是主要屈肘肌）',
    palpation: '上臂前下段，肱二頭肌兩側邊緣往深處按（外側較易摸到）。',
    release: '屈肘放鬆，拇指從肱二頭肌外側緣推入撥揉。筆記：大腸經、心經相關肌。',
    referral: '拇指根部、肘前', symptoms: ['肘前痛', '拇指根痛'], points: ['LI11', 'LU5'], sinew: ['LI', 'HT'] },
  { id: 'pronator', name: '旋前圓肌／旋前方肌', en: 'Pronator teres & quadratus', region: '上肢', layer: '中層', r: 0.005, deep: true,
    origin: '旋前圓肌：肱骨內上髁、尺骨冠突；旋前方肌：尺骨遠端前面', insertion: '旋前圓肌：橈骨中段外側；旋前方肌：橈骨遠端前面', action: '前臂旋前；旋前圓肌協助屈肘',
    palpation: '肘窩內下方斜向橈骨中段的肌腹（孔最附近）；旋前方肌在腕橫紋上方深層。',
    release: '筆記：旋前主要肌，連到屈腕肌群 → 肱骨內上髁（高爾夫球肘）。由內上髁往橈骨中段斜向撥揉。正中神經可能穿過旋前圓肌兩頭之間，麻感時力道放輕。',
    referral: '前臂掌側、拇指側', symptoms: ['高爾夫球肘', '前臂痛', '手麻'], points: ['LU6', 'PC3', 'HT3'], sinew: ['LU', 'PC'] },
  { id: 'supinator', name: '旋後肌', en: 'Supinator', region: '上肢', layer: '深層', r: 0.005, deep: true,
    origin: '肱骨外上髁、尺骨旋後肌嵴', insertion: '橈骨上段外側', action: '前臂旋後（與肱二頭肌共同）',
    palpation: '肘外側下方 2–3 指、肱橈肌與伸腕肌之間的深處（手三里附近）。',
    release: '筆記：旋後主要肌（旋後肌、肱二頭肌），連伸肌群 → 肱骨外上髁（網球肘）。前臂反覆旋前旋後時持續壓放。橈神經深支穿過此肌。',
    referral: '肘外側、前臂背側', symptoms: ['網球肘', '前臂外側痛'], points: ['LI10', 'LI11'], sinew: ['LI', 'TE'] },
  { id: 'int_oblique', name: '腹內斜肌', en: 'Internal oblique', region: '腹', layer: '中層', r: 0.006,
    origin: '胸腰筋膜、髂嵴、腹股溝韌帶外側', insertion: '下位肋骨、腹白線、恥骨', action: '軀幹同側旋轉、側屈；增加腹壓；吐氣',
    palpation: '側腹，腹外斜肌深層；纖維方向與腹外斜肌交叉（往內上）。',
    release: '筆記（呼吸）：「髂棘到肋骨」的呼吸肌之一（腹內外斜、腹橫、腹直）。側臥由髂嵴往肋弓推。',
    referral: '下腹、鼠蹊', symptoms: ['側腹痛', '呼吸淺'], points: ['GB26', 'LR13'], sinew: ['SP', 'LR'] },
  { id: 'vastus_int', name: '股中間肌', en: 'Vastus intermedius', region: '大腿', layer: '深層', r: 0.008, deep: true,
    origin: '股骨前面與外側面上 2/3', insertion: '經股四頭肌腱 → 髕骨 → 脛骨粗隆', action: '伸膝',
    palpation: '股直肌深層，從大腿前面兩側推開股直肌往深處按。',
    release: '筆記：胃經相關肌（股直肌、股中間肌）。仰臥屈膝，掌根由膝往髖推。',
    referral: '大腿前側', symptoms: ['大腿前側緊', '膝前痛'], points: ['ST32', 'ST34'], sinew: ['ST'] },
  { id: 'popliteus', name: '膕肌', en: 'Popliteus', region: '小腿', layer: '深層', r: 0.005, deep: true,
    origin: '股骨外髁外側', insertion: '脛骨後面上段（比目魚肌線以上）', action: '膝解鎖：屈膝初期使脛骨內旋；膝伸直最後 30° 時脛骨向外轉約 10°（筆記）',
    palpation: '膝後膕窩下方斜向內下，委中下方深層。',
    release: '筆記：膕肌會拉到內側半月板、影響後十字韌帶；屈膝時與膕弓韌帶把外半月板往後拉。輕揉委中下方（有血管神經），配合脛骨內外旋。',
    referral: '膝後', symptoms: ['膝後痛', '膝卡住'], points: ['BL40', 'BL39'], sinew: ['BL'] },
  { id: 'toe_ext', name: '伸趾長肌／伸趾短肌', en: 'Extensor digitorum longus & brevis', region: '小腿', layer: '淺層', r: 0.005,
    origin: '伸趾長肌：脛骨外髁、腓骨前緣；伸趾短肌：跟骨背外側', insertion: '第 2–5 趾背', action: '伸趾；協助踝背屈、外翻',
    palpation: '脛前肌外側、小腿前外側（胃經、膽經之間）；足背外側隆起處為伸趾短肌。',
    release: '由踝往膝推小腿前外側；腳趾翹起壓不下去時常與脛前肌一起緊。',
    referral: '足背', symptoms: ['足背痛', '小腿前外側緊'], points: ['ST36', 'ST41', 'GB40'], sinew: ['ST', 'GB'] },
  { id: 'tfl_itb', name: '闊筋膜張肌／髂脛束', en: 'TFL & iliotibial band', region: '髖', layer: '淺層', r: 0.0065, inset: 0.003,
    origin: '髂前上棘外側、髂嵴前部', insertion: '經髂脛束至脛骨外髁（Gerdy 結節）',
    action: '髖屈曲、外展、內旋；穩定膝外側', palpation: '髂前上棘外下方的小肌腹，往下為大腿外側堅韌的帶子（膽經風市）。',
    release: '側臥，滾法、掌根推大腿外側（髂脛束本身不太會「放鬆」，重點放在闊筋膜張肌與股外側肌）。',
    referral: '髖外側、大腿外側到膝', symptoms: ['膝外側痛', '大腿外側緊', '骨盆前傾'], points: ['GB31', 'GB32', 'GB33', 'GB29'], sinew: ['GB', 'ST'],
    fibers: [[['OFF', ['LM', 'ASIS'], 0.012, -0.004, -0.008], ['L', 'thigh', 0.08, 72, 0.002], ['L', 'thigh', 0.45, 92, 0.002], ['L', 'thigh', 0.85, 98, 0.002], ['LM', 'gerdy']], [['LM', 'crestTop'], ['L', 'thigh', 0.06, 100, 0.002], ['L', 'thigh', 0.5, 100, 0.002], ['L', 'thigh', 0.9, 100, 0.002], ['LM', 'gerdy']]] },
  { id: 'rectus_fem', name: '股直肌', en: 'Rectus femoris', region: '大腿', layer: '淺層', r: 0.0085, inset: 0.006,
    origin: '髂前下棘', insertion: '經髕骨、髕韌帶至脛骨粗隆', action: '伸膝、屈髖；骨盆前傾',
    palpation: '大腿前側正中（胃經伏兔）。', release: '仰臥滾法、拿法；俯臥屈膝伸展。骨盆前傾者縮短。',
    referral: '膝前、髕骨周圍', symptoms: ['膝前痛', '骨盆前傾', '上下樓梯痛'], points: ['ST31', 'ST32', 'ST34'], sinew: ['ST'],
    fibers: [[['LM', 'AIIS'], ['L', 'thigh', 0.15, 12, 0.006], ['L', 'thigh', 0.55, 0, 0.006], ['L', 'thigh', 0.92, 0, 0.004], ['LM', 'patella']]] },
  { id: 'vastus_lat', name: '股外側肌', en: 'Vastus lateralis', region: '大腿', layer: '淺層', r: 0.009, inset: 0.007,
    origin: '大轉子、股骨粗線外唇', insertion: '髕骨外緣、髕韌帶', action: '伸膝；過緊使髕骨外移',
    palpation: '大腿前外側。', release: '側臥滾法、掌推；梁丘一帶點按。', referral: '大腿外側、膝外側', symptoms: ['膝外側痛', '髕骨外移'],
    points: ['ST34', 'GB31', 'GB32'], sinew: ['ST', 'GB'],
    fibers: [[['OFF', ['LM', 'gTroch'], 0, -0.03, 0.01], ['L', 'thigh', 0.35, 70, 0.006], ['L', 'thigh', 0.75, 50, 0.006], ['OFF', ['LM', 'patella'], 0.012, 0.01, -0.006]], [['L', 'thigh', 0.15, 95, 0.006], ['L', 'thigh', 0.5, 88, 0.006], ['L', 'thigh', 0.85, 65, 0.005], ['OFF', ['LM', 'patella'], 0.014, 0.0, -0.008]]] },
  { id: 'vastus_med', name: '股內側肌', en: 'Vastus medialis (VMO)', region: '大腿', layer: '淺層', r: 0.0085, inset: 0.007,
    origin: '股骨粗線內唇', insertion: '髕骨內緣', action: '伸膝最後 15°、穩定髕骨內側',
    palpation: '膝內上方的水滴狀肌肉（脾經血海）。', release: '多需強化；痠痛時拿揉血海一帶。', referral: '膝內側', symptoms: ['膝內側痛', '膝無力', '髕骨外移'],
    points: ['SP10'], sinew: ['SP'],
    fibers: [[['L', 'thigh', 0.3, 300, 0.012], ['L', 'thigh', 0.7, 305, 0.006], ['L', 'thigh', 0.9, 320, 0.004], ['OFF', ['LM', 'patella'], -0.012, 0.004, -0.006]]] },
  { id: 'adductors', name: '內收肌群', en: 'Adductors', region: '大腿', layer: '淺層', r: 0.0085, inset: 0.008,
    origin: '恥骨上枝、下枝、坐骨枝', insertion: '股骨粗線、內收肌結節（股薄肌至鵝足）', action: '髖內收；部分屈髖或伸髖；穩定骨盆',
    palpation: '大腿內側（肝經、腎經、脾經經過區）。', release: '仰臥 4 字位或屈膝外展，拿法與掌推由膝往鼠蹊（近鼠蹊處力道輕）。恥骨聯合歪斜、骨盆前後傾常牽連。',
    referral: '鼠蹊、大腿內側、膝內側', symptoms: ['鼠蹊痛', '膝內側痛', '恥骨痛', '骨盆歪斜'], points: ['LR10', 'LR11', 'LR9', 'SP11'], sinew: ['LR', 'SP', 'KI'],
    fibers: [[['LM', 'pubicTub'], ['L', 'thigh', 0.2, 285, 0.008], ['L', 'thigh', 0.45, 255, 0.014]], [['LM', 'pubicRamusInf'], ['L', 'thigh', 0.35, 265, 0.008], ['L', 'thigh', 0.82, 255, 0.008], ['LM', 'femMedCond']], [['OFF', ['LM', 'pubicSym'], 0.012, -0.012, -0.004], ['L', 'thigh', 0.4, 245, 0.004], ['L', 'thigh', 0.95, 240, 0.004], ['LM', 'pesAns']]] },
  { id: 'sartorius', name: '縫匠肌', en: 'Sartorius', region: '大腿', layer: '淺層', r: 0.0055, inset: 0.003,
    origin: '髂前上棘', insertion: '脛骨內側上端（鵝足）', action: '屈髖、外展外旋髖、屈膝（盤腿動作）',
    palpation: '從髂前上棘斜向大腿內側到膝內下。', release: '沿走向輕推；鵝足處彈撥。', referral: '大腿前內側', symptoms: ['膝內側痛', '鵝足炎'],
    points: ['SP10'], sinew: ['SP', 'LR'],
    fibers: [[['LM', 'ASIS'], ['L', 'thigh', 0.18, 25, 0.002], ['L', 'thigh', 0.5, 320, 0.002], ['L', 'thigh', 0.85, 278, 0.003], ['LM', 'pesAns']]] },
  { id: 'hamstrings', name: '膕繩肌（股二頭、半腱、半膜）', en: 'Hamstrings', region: '大腿', layer: '淺層', r: 0.009, inset: 0.008,
    origin: '坐骨粗隆（股二頭短頭：股骨粗線）', insertion: '腓骨頭（股二頭）；脛骨內髁（半腱、半膜）',
    action: '屈膝、伸髖；骨盆後傾', palpation: '大腿後側；膝窩兩側肌腱。',
    release: '俯臥滾法、拿法、肘推殷門一帶；直腿抬高伸展。骨盆後傾者縮短；前傾者常是被拉長的痠緊。',
    referral: '臀橫紋、大腿後、膝窩', symptoms: ['大腿後痛', '骨盆後傾', '坐骨神經痛', '彎腰受限'], points: ['BL36', 'BL37', 'BL39', 'BL40'], sinew: ['BL'],
    fibers: [[['LM', 'ischTub'], ['L', 'thigh', 0.3, 188, 0.006], ['L', 'thigh', 0.75, 150, 0.006], ['LM', 'fibHead']], [['LM', 'ischTub'], ['L', 'thigh', 0.3, 205, 0.006], ['L', 'thigh', 0.75, 228, 0.006], ['OFF', ['LM', 'tibMedCond'], 0, -0.01, -0.015]], [['LM', 'ischTub'], ['L', 'thigh', 0.35, 220, 0.008], ['L', 'thigh', 0.8, 240, 0.008], ['OFF', ['LM', 'tibMedCond'], 0.002, -0.004, -0.02]]] },
  // ===== 小腿／足 =====
  { id: 'gastroc', name: '腓腸肌', en: 'Gastrocnemius', region: '小腿', layer: '淺層', r: 0.01, inset: 0.007,
    origin: '股骨內、外髁後面', insertion: '經跟腱至跟骨', action: '踝蹠屈、屈膝',
    palpation: '小腿肚兩個肌腹（承筋、承山）。', release: '俯臥拿捏、推法、點按承山；跟腱輕撥。抽筋、久站者常緊。',
    referral: '小腿肚、足弓、膝窩', symptoms: ['小腿抽筋', '足底筋膜炎', '膝窩痛', '跟腱痛'], points: ['BL57', 'BL56', 'BL55', 'BL40'], sinew: ['BL'],
    fibers: [[['OFF', ['LM', 'femMedCond'], 0, 0.012, -0.018], ['L', 'leg', 0.22, 220, 0.004], ['L', 'leg', 0.5, 195, 0.008], ['L', 'leg', 0.82, 180, 0.012], ['LM', 'calcaneus']], [['OFF', ['LM', 'femLatCond'], 0, 0.012, -0.018], ['L', 'leg', 0.22, 145, 0.004], ['L', 'leg', 0.5, 165, 0.008], ['L', 'leg', 0.82, 178, 0.012], ['LM', 'calcaneus']]] },
  { id: 'soleus', name: '比目魚肌', en: 'Soleus', region: '小腿', layer: '中層', r: 0.0085, inset: 0.018,
    origin: '腓骨頭與上段後面、脛骨比目魚肌線', insertion: '經跟腱至跟骨', action: '踝蹠屈（站姿穩定、小腿的「第二心臟」）',
    palpation: '腓腸肌深層、兩側邊緣可在小腿中下段摸到。', release: '俯臥屈膝 90°，拇指沿小腿兩側往深處撥；屈膝狀態下背屈伸展。',
    referral: '腳跟、薦髂關節（少見）', symptoms: ['足跟痛', '小腿腫脹', '小腿抽筋'], points: ['BL57', 'BL58', 'KI9'], sinew: ['BL', 'KI'],
    fibers: [[['L', 'leg', 0.12, 150, 0.02], ['L', 'leg', 0.5, 165, 0.014], ['L', 'leg', 0.85, 178, 0.012], ['LM', 'calcaneus']], [['L', 'leg', 0.15, 210, 0.02], ['L', 'leg', 0.55, 200, 0.014], ['L', 'leg', 0.85, 185, 0.012], ['LM', 'calcaneus']]] },
  { id: 'tib_ant', name: '脛前肌', en: 'Tibialis anterior', region: '小腿', layer: '淺層', r: 0.0065, inset: 0.006,
    origin: '脛骨外側面上 2/3', insertion: '內側楔骨、第 1 蹠骨底', action: '踝背屈、足內翻',
    palpation: '脛骨前緣外側（胃經足三里—條口一帶）。', release: '仰臥推法由踝往膝、拇指撥；足三里點按。',
    referral: '腳踝前、大拇趾', symptoms: ['脛前痛', '足下垂', '腳踝痛'], points: ['ST36', 'ST38', 'ST40', 'ST41'], sinew: ['ST'],
    fibers: [[['L', 'leg', 0.08, 42, 0.006], ['L', 'leg', 0.5, 30, 0.006], ['L', 'leg', 0.88, 355, 0.005], ['FT', 0.4, -0.5, 'd'], ['LM', 'base1MT']]] },
  { id: 'peroneus', name: '腓骨長短肌', en: 'Peroneus longus & brevis', region: '小腿', layer: '淺層', r: 0.0058, inset: 0.006,
    origin: '腓骨頭與外側面', insertion: '第 5 蹠骨底（短肌）；繞足底至第 1 蹠骨底（長肌）', action: '足外翻、蹠屈；穩定足弓',
    palpation: '小腿外側（膽經陽陵泉以下）。', release: '側臥推法、彈撥；扭傷後常有沾黏。', referral: '外踝、足外側', symptoms: ['腳踝扭傷', '外踝痛', '腳踝不穩'],
    points: ['GB34', 'GB36', 'GB39', 'BL60'], sinew: ['GB'],
    fibers: [[['L', 'leg', 0.06, 108, 0.004], ['L', 'leg', 0.5, 112, 0.005], ['L', 'leg', 0.9, 145, 0.004], ['OFF', ['LM', 'latMall'], 0.0, -0.018, -0.006], ['LM', 'base5MT']]] },
  { id: 'tib_post', name: '脛後肌', en: 'Tibialis posterior', region: '小腿', layer: '深層', r: 0.006, deep: true,
    origin: '脛骨、腓骨後面與骨間膜', insertion: '舟狀骨粗隆、楔骨、蹠骨底', action: '足內翻、蹠屈；支撐內側足弓',
    palpation: '內踝後上方、脛骨內緣後方深層。', release: '拇指沿脛骨內緣後方深撥（脾經三陰交一帶）。扁平足者多無力。',
    referral: '跟腱、足底', symptoms: ['扁平足', '內踝痛', '脛骨內側痛'], points: ['SP6', 'KI7', 'KI3'], sinew: ['SP', 'KI'],
    fibers: [[['X', 0.11, 0.42, -0.02], ['X', 0.098, 0.25, -0.02], ['X', 0.08, 0.11, -0.022], ['OFF', ['LM', 'medMall'], 0.0, -0.016, -0.012], ['LM', 'navicular']]] },
  { id: 'plantar', name: '足底筋膜／足底肌', en: 'Plantar fascia', region: '足', layer: '淺層', r: 0.0055, inset: 0.0,
    origin: '跟骨內側結節', insertion: '五趾蹠趾關節（趾基部）', action: '維持縱向足弓、絞盤機制',
    palpation: '足底；腳跟前內側最常壓痛。', release: '拇指由腳跟往趾推、點按湧泉；滾球放鬆。常與小腿後側一起緊。',
    referral: '腳跟、足弓', symptoms: ['足底筋膜炎', '足跟痛', '扁平足'], points: ['KI1', 'KI2'], sinew: ['KI'],
    fibers: [-0.7, 0.0, 0.7].map((w) => [['FT', 0.06, -0.1, 'p'], ['FT', 0.4, w * 0.6, 'p'], ['FT', 0.78, w, 'p']]) },
];

/* 神經支配（肌動學通識；肩部依課堂筆記核對） */
(function () {
  const N = {
    scm: '副神經（CN XI）、C2–C3', scalene: '頸神經前支（C3–C8）', trap_u: '副神經（筆記：副）', trap_m: '副神經（筆記：副）', trap_l: '副神經（筆記：副）',
    levator: '肩胛背神經 C3–C5（筆記：肩胛背）', splenius: '頸神經後支', subocc: '枕下神經（C1）', masseter: '三叉神經下頜支', temporalis: '三叉神經下頜支',
    rhomboid: '肩胛背神經 C4–C5（筆記：肩胛背）', supraspinatus: '肩胛上神經 C5–C6（筆記：肩胛上）', infraspinatus: '肩胛上神經 C5–C6（筆記：肩胛上）', teres_minor: '腋神經 C5–C6（筆記：腋）',
    teres_major: '下肩胛下神經 C5–C7（筆記：肩胛下）', subscap: '上、下肩胛下神經 C5–C7（筆記：肩胛下）', lat: '胸背神經 C6–C8（筆記：胸背）', serratus: '長胸神經 C5–C7（筆記：長胸）',
    pec_major: '胸內、外側神經 C5–T1（筆記：胸）', pec_minor: '胸內側神經 C8–T1（筆記：胸）', deltoid: '腋神經 C5–C6（筆記：腋）', biceps: '肌皮神經 C5–C6（筆記：肌皮）', triceps: '橈神經 C6–C8（筆記：橈）',
    brachiorad: '橈神經 C5–C6', forearm_ext: '橈神經／後骨間神經 C6–C8', forearm_flex: '正中神經、尺神經 C6–T1', brachialis: '肌皮神經（外側部另有橈神經）C5–C6', pronator: '正中神經 C6–C7（筆記：正中神經會穿過旋前圓肌）', supinator: '橈神經深支 C5–C6（筆記：橈神經經過旋後肌）',
    erector: '脊神經後支', multifidus: '脊神經後支', ql: 'T12–L4 前支', rectus_abd: '肋間神經 T7–T12', ext_oblique: '肋間神經 T7–T12、肋下神經', int_oblique: 'T7–L1（肋間、髂腹下、髂腹股溝神經）', diaphragm: '膈神經 C3–C5（筆記：膈神經 → 胃脹、打嗝）',
    iliopsoas: '腰神經叢前支 L1–L3、股神經', glute_max: '臀下神經 L5–S2', glute_med: '臀上神經 L4–S1', glute_min: '臀上神經 L4–S1', tfl_itb: '臀上神經 L4–S1', piriformis: '梨狀肌神經 S1–S2',
    deep_rot: '閉孔內肌神經、股方肌神經 L4–S2；閉孔外肌為閉孔神經', rectus_fem: '股神經 L2–L4', vastus_lat: '股神經 L2–L4', vastus_med: '股神經 L2–L4', vastus_int: '股神經 L2–L4',
    adductors: '閉孔神經 L2–L4（內收大肌後部：坐骨神經；恥骨肌：股神經）', sartorius: '股神經 L2–L3', hamstrings: '坐骨神經（脛神經部；股二頭肌短頭為腓總神經）L5–S2',
    gastroc: '脛神經 S1–S2', soleus: '脛神經 S1–S2', popliteus: '脛神經 L4–S1', tib_post: '脛神經 L4–L5', tib_ant: '腓深神經 L4–L5', toe_ext: '腓深神經 L5–S1', peroneus: '腓淺神經 L5–S1', plantar: '足底內、外側神經',
  };
  (window.MUSCLES || []).forEach((m) => { if (N[m.id]) m.nerve = N[m.id]; });
})();
