/* ===== 評估：觀察項目、模式規則、連鎖關係 ===== */

/* 觀察／測試項目。side:true 代表要指定左右 */
window.FINDINGS = [
  { group: '主訴', items: [
    { id: 'c_head_front', label: '前額頭痛' }, { id: 'c_head_side', label: '偏頭痛（側頭）', side: true }, { id: 'c_head_back', label: '後頭痛' }, { id: 'c_head_top', label: '巔頂痛' },
    { id: 'c_neck', label: '頸痛／轉頭受限', side: true }, { id: 'c_neckstiff', label: '肩頸僵硬' }, { id: 'c_jaw', label: '顳顎／咬合痛', side: true },
    { id: 'c_sh_front', label: '肩前痛', side: true }, { id: 'c_sh_raise', label: '舉手痛／舉不高', side: true }, { id: 'c_scap_between', label: '肩胛間痛' },
    { id: 'c_arm_numb', label: '手麻', side: true }, { id: 'c_elbow_lat', label: '手肘外側痛', side: true }, { id: 'c_elbow_med', label: '手肘內側痛', side: true }, { id: 'c_wrist', label: '手腕痛', side: true },
    { id: 'c_chest', label: '胸悶／呼吸淺' }, { id: 'c_lbp', label: '下背痛', side: true }, { id: 'c_lbp_acute', label: '閃到腰（急性）', side: true },
    { id: 'c_si', label: '薦髂／臀部痛', side: true }, { id: 'c_sciatic', label: '臀腿後側放射痛', side: true }, { id: 'c_groin', label: '鼠蹊／恥骨痛', side: true },
    { id: 'c_thigh_lat', label: '大腿外側緊痛', side: true }, { id: 'c_knee_front', label: '膝前痛', side: true }, { id: 'c_knee_med', label: '膝內側痛', side: true }, { id: 'c_knee_lat', label: '膝外側痛', side: true }, { id: 'c_knee_back', label: '膝後痛', side: true },
    { id: 'c_calf', label: '小腿緊／抽筋', side: true }, { id: 'c_ankle', label: '腳踝痛／舊扭傷', side: true }, { id: 'c_heel', label: '足底／腳跟痛', side: true },
  ] },
  { group: '視診（站姿）', items: [
    { id: 'o_head_fwd', label: '頭前傾（耳垂在肩峰前）' }, { id: 'o_head_tilt', label: '頭側傾', side: true, sideLabel: '傾向' },
    { id: 'o_sh_high', label: '高低肩', side: true, sideLabel: '高側' }, { id: 'o_round', label: '圓肩' }, { id: 'o_wing', label: '翼狀肩胛', side: true }, { id: 'o_kyph', label: '駝背（胸椎後凸）' },
    { id: 'o_lordosis', label: '腰椎前凸增加／臀翹' }, { id: 'o_flatback', label: '腰平／臀平' }, { id: 'o_crest_high', label: '髂嵴高低', side: true, sideLabel: '高側' },
    { id: 'o_scoli', label: '脊椎側彎', side: true, sideLabel: '凸側(腰)' }, { id: 'o_knee_o', label: 'O 型腿（膝內翻）' }, { id: 'o_knee_x', label: 'X 型腿（膝外翻）' },
    { id: 'o_flatfoot', label: '扁平足／足弓塌', side: true }, { id: 'o_pregnant', label: '孕期／產後' },
    { id: 'o_lean_down', label: '身體向痛側側彎（痛側在下）', side: true, sideLabel: '痛側' }, { id: 'o_lean_up', label: '身體傾向健側（痛側在上）', side: true, sideLabel: '痛側' },
  ] },
  { group: '觸診與測試', items: [
    { id: 't_muscle', label: '主動動作痛、被動不痛（三分法→肌肉）' }, { id: 't_joint', label: '主動、被動都不足且痛（三分法→骨／關節）' }, { id: 't_nerve', label: '主動不足但不痛、被動可動（三分法→神經）' },
    { id: 't_psis_high', label: '俯臥：髂後上棘較高', side: true }, { id: 't_psis_low', label: '俯臥：髂後上棘較低', side: true },
    { id: 't_psis_far', label: '俯臥：髂後上棘離 S2 中線較遠（同一水平）', side: true }, { id: 't_psis_near', label: '俯臥：髂後上棘離中線較近', side: true },
    { id: 't_psis_upfar', label: '俯臥：髂後上棘又高又遠（第三角度 EX）', side: true }, { id: 't_psis_lownear', label: '俯臥：髂後上棘又低又近（第三角度 IN）', side: true },
    { id: 't_heel_long', label: '俯臥／仰臥：足跟較長（長腳）', side: true }, { id: 't_heel_buttock', label: '俯臥屈膝：足跟離臀部較近', side: true }, { id: 't_isch_high', label: '俯臥：坐骨結節較高', side: true }, { id: 't_isch_low', label: '俯臥：坐骨結節較低、臀部下垂', side: true }, { id: 't_heel_buttock_far', label: '俯臥屈膝：足跟離臀部較遠', side: true },
    { id: 't_scap_sitlie', label: '坐姿轉臥姿：肩胛相對位置改變', side: true }, { id: 't_scap_same', label: '坐姿轉臥姿：肩胛位置不變（骨盆正）', side: true },
    { id: 't_troch_thick', label: '大轉子摸起來較厚', side: true }, { id: 't_troch_thin', label: '大轉子摸起來較薄、尖', side: true },
    { id: 't_heel_out', label: '俯臥屈膝 90°：足跟偏向外', side: true }, { id: 't_heel_short', label: '俯臥／仰臥：足跟較短（短腳）', side: true },
    { id: 't_rot_limited', label: '俯臥小腿內外旋：較打不開的一側', side: true }, { id: 't_stl_tight', label: '薦結節韌帶較緊、滑動差', side: true },
    { id: 't_slr_mid', label: '直腿抬高 45–70° 痛，>70° 反而不痛', side: true }, { id: 't_slr_low', label: '直腿抬高 <45° 就放射到小腿／腳', side: true },
    { id: 't_thomas', label: 'Thomas 測試：大腿抬起（髖屈肌緊）', side: true }, { id: 't_trend', label: '單腳站時對側骨盆下掉', side: true, sideLabel: '站立腳' },
    { id: 't_neck_rot', label: '轉頭到對側受限＋肩胛上角壓痛', side: true }, { id: 't_infra', label: '天宗壓痛並放射到肩前', side: true },
    { id: 't_scalene', label: '缺盆上方斜角肌壓痛、手麻重現', side: true }, { id: 't_pecmin', label: '喙突下方壓痛（胸小肌）', side: true },
    { id: 't_knee_flex', label: '膝越彎越痛／會卡住', side: true }, { id: 't_pes', label: '鵝足（膝內下）壓痛', side: true }, { id: 't_itb', label: '膝外上方（膝陽關）壓痛', side: true },
    { id: 't_df_limited', label: '踝背屈受限（蹲下腳跟離地）', side: true }, { id: 't_bone_tender', label: '骨頭局部壓痛、輕敲鑽痛' },
  ] },
  { group: '安全警訊（出現請先轉介）', items: [
    { id: 'r_trauma', label: '外傷後劇痛、變形、腫脹' }, { id: 'r_night', label: '夜間痛、發燒、體重減輕' }, { id: 'r_saddle', label: '大小便異常、會陰麻木' },
    { id: 'r_weak', label: '進行性無力、肌肉萎縮' }, { id: 'r_chest', label: '胸痛合併冒冷汗或喘' }, { id: 'r_headache', label: '突發劇烈頭痛／口齒不清' },
  ] },
];

/* 模式：t = 觸發項目與權重；tight/weak = [肌肉, 'same'|'opp'|'both', 權重]
   side 由帶有左右的觸發項推得（same=同側，opp=對側） */
window.PATTERNS = [
  { id: 'p_ant', name: '骨盆前傾（第一角度 A）', region: ['pelvis', 'lspine'], src: '課堂 0727、0810、0907',
    desc: '無名骨繞 S2 橫軸向前轉。站姿臀翹、腰椎前凸增加；俯臥髂後上棘較 S2 高、坐骨結節較高、屈膝時足跟離臀部較近；A 側為長腳（筆記）。可單側或雙側，臨床多為一側 A、另一側 P。筆記：A 的相關肌為腰大肌、股直肌。',
    t: { o_lordosis: 3, t_psis_high: 3, t_thomas: 2, t_heel_long: 2, t_heel_buttock: 2, t_isch_high: 2, c_lbp: 1 },
    tight: [['iliopsoas', 'same', 3], ['rectus_fem', 'same', 2], ['erector', 'both', 2], ['tfl_itb', 'same', 1], ['lat', 'both', 1]],
    weak: [['glute_max', 'same', 2], ['hamstrings', 'same', 1], ['rectus_abd', 'both', 1]],
    points: ['BL23', 'BL25', 'ST31', 'SP12', 'GB29'], chain: ['lspine', 'hip', 'knee'],
    tech: '先處理股直肌（唯一跨髖的股四頭肌，起於髂前下棘）與髂腰肌，再放鬆腰部豎脊肌。後側被拉長的臀大肌與膕繩肌是「被拉長的痛」，以伸展為輔、日後強化。' },
  { id: 'p_post', name: '骨盆後傾（第一角度 P）', region: ['pelvis', 'lspine'], src: '課堂 0727、0817',
    desc: '無名骨向後轉，臀部扁平、腰椎曲度變平；俯臥髂後上棘較低；P 側為短腿（筆記）。筆記：P 的相關肌為半腱肌（半膜肌）、股二頭肌長頭。',
    t: { o_flatback: 3, t_psis_low: 3, t_heel_short: 2, t_isch_low: 2, t_heel_buttock_far: 2, c_lbp: 1, o_kyph: 1 },
    tight: [['hamstrings', 'same', 3], ['glute_max', 'same', 2], ['rectus_abd', 'both', 2]],
    weak: [['iliopsoas', 'same', 2], ['erector', 'both', 1]],
    points: ['BL36', 'BL37', 'BL40', 'CV6'], chain: ['lspine', 'tspine'],
    tech: '膕繩肌（殷門一帶）與臀大肌放鬆、腹直肌下段放鬆，再看腰椎曲度是否恢復。' },
  { id: 'p_ex', name: '骨盆外轉（第二角度 EX）', region: ['pelvis', 'hip', 'lspine'], src: '課堂 0810、0817、筆記',
    desc: '俯臥摸髂後上棘與 S2 的距離：同一水平線上、離 S2 較遠為 EX（筆記：「遠離 S2，圓」）。俯臥屈膝 90° 時腿較外轉、大轉子摸起來較厚、臀部外觀較垂直。第二角度會造成脊椎逆向旋轉（筆記）。',
    t: { t_psis_far: 3, t_troch_thick: 2, t_heel_out: 2, t_stl_tight: 1, c_si: 1, c_thigh_lat: 1 },
    tight: [['glute_med', 'same', 3], ['glute_min', 'same', 3], ['tfl_itb', 'same', 3]],
    weak: [['deep_rot', 'same', 1], ['piriformis', 'same', 1]],
    points: ['GB29', 'GB30', 'GB31'], chain: ['lspine', 'hip', 'knee'],
    tech: '筆記：② EX 處理臀中肌、臀小肌、闊筋膜張肌。居髎（臀中小肌前束、闊筋膜張肌）一帶沿肌纖維方向壓放，做完重新量 EX/IN；臀後六肌此時多半是被拉長的一方，不是主要處理對象。' },
  { id: 'p_in', name: '骨盆內轉（第二角度 IN）', region: ['pelvis', 'hip', 'sacrum'], src: '課堂 0810、0817、筆記',
    desc: '髂後上棘與 S2 在同一水平線上、離 S2 較近為 IN。大轉子摸起來較薄、尖。',
    t: { t_psis_near: 3, t_troch_thin: 2, c_si: 1, c_sciatic: 1 },
    tight: [['deep_rot', 'same', 3], ['piriformis', 'same', 3]],
    weak: [['glute_med', 'same', 1], ['tfl_itb', 'same', 1]],
    points: ['GB30', 'BL54', 'BL28'], chain: ['hip', 'sacrum', 'knee'],
    tech: '筆記：② IN 處理臀後六肌（梨狀肌、閉孔內外肌、上下孖肌、股方肌）。大轉子後方到薦椎外緣之間，找最緊的一條沿纖維方向垂直下壓、持續壓放；坐骨神經在梨狀肌下方，避免重壓坐骨大孔。' },
  { id: 'p_3ex', name: '骨盆第三角度 EX（耳狀面外展）', region: ['pelvis', 'lspine', 'pubis'], src: '課堂 0817、筆記',
    desc: '耳狀面是斜的，無名骨沿著它斜斜向上、向外：髂後上棘離 S2「又高又遠」，相當於第一角度 A（高）＋第二角度 EX（遠）同時出現。課堂說明：股骨不動時等於把腳往上帶 → 短腿；造成腰椎直接側彎（無旋轉），常伴鼠蹊痛。',
    t: { t_psis_upfar: 4, t_heel_short: 1, o_crest_high: 1, c_groin: 1, o_scoli: 1 },
    tight: [['glute_med', 'same', 3], ['glute_min', 'same', 3], ['tfl_itb', 'same', 3], ['ql', 'same', 1]],
    weak: [['adductors', 'same', 1]],
    points: ['GB29', 'GB30', 'BL52', 'GB25'], chain: ['lspine', 'pubis', 'knee', 'ankle'],
    tech: '筆記：③ EX 的肌肉與 ② EX 相同（臀中、臀小、闊筋膜張肌），但手法不同。短腿要先知道「為什麼短」再處理，不要直接拉腿；處理後重新量三個角度，常會變成另一個角度的問題。' },
  { id: 'p_3in', name: '骨盆第三角度 IN（耳狀面內收）', region: ['pelvis', 'pubis', 'hip'], src: '課堂 0817、筆記',
    desc: '與 ③ EX 相反：無名骨沿耳狀面斜向下、向內，髂後上棘離 S2「又低又近」，相當於第一角度 P（低）＋第二角度 IN（近）。',
    t: { t_psis_lownear: 4, c_groin: 2, o_crest_high: 1 },
    tight: [['adductors', 'same', 3]],
    weak: [['glute_med', 'same', 1], ['tfl_itb', 'same', 1]],
    points: ['LR10', 'LR11', 'SP11', 'KI11'], chain: ['pubis', 'hip', 'knee'],
    tech: '筆記：③ IN 處理內收肌群——內收大肌、內收長肌、內收短肌、恥骨肌、股薄肌。大腿內側由膝往鼠蹊分段放鬆（股薄肌經過鵝足，可順帶看膝內側）；鼠蹊處有股動脈、神經，力道放輕。' },
  { id: 'p_sacrum', name: '薦椎扭轉／卡住', region: ['sacrum', 'lspine', 'pelvis'], src: '課堂筆記（薦椎）、0727',
    desc: '薦椎是腰椎的底座。自然步態沿斜軸做 Right on Right、Left on Left；步態異常或翹腳、半躺等非自然姿勢可卡在 10 種狀態之一（向前點頭、向後反點頭、R on R、L on L、R on L、L on R、左右單邊向前／向後）。',
    t: { t_rot_limited: 3, c_si: 2, t_heel_short: 1, c_lbp: 1, o_pregnant: 1 },
    tight: [['piriformis', 'both', 2], ['multifidus', 'same', 2], ['ql', 'same', 1], ['glute_max', 'same', 1]],
    weak: [],
    points: ['BL31', 'BL32', 'BL33', 'BL34', 'BL28', 'GV3'], chain: ['lspine', 'pelvis'],
    tech: '檢查順序（筆記）：①俯臥托腿讓脊椎被撐起、肌肉放鬆，觀察最真實的薦椎；②屈膝看兩側跟骨是否一樣高；③抬小腿做內外旋，較打不開的一側可能是薦髂關節、髖關節或附近肌肉卡住。' },
  { id: 'p_piri', name: '梨狀肌症候群（假性坐骨神經痛）', region: ['hip', 'sacrum'], src: '課堂 0810',
    desc: '坐骨神經由梨狀肌下方（或穿過肌腹）出來。股骨外轉、骨盆 EX 時梨狀肌被拉緊，擠壓坐骨神經。',
    t: { t_slr_mid: 4, c_sciatic: 2, c_si: 1, t_troch_thick: 1 },
    tight: [['piriformis', 'same', 3], ['glute_max', 'same', 1], ['glute_min', 'same', 1]],
    weak: [],
    points: ['GB30', 'BL54', 'BL37', 'BL40'], chain: ['hip', 'knee'],
    tech: '鑑別：仰臥直腿抬高 45° 後開始痛、60–70° 最痛、超過 70° 反而不痛 → 強烈懷疑梨狀肌。坐骨神經由 L4–S3 組成，於膕窩分為脛神經與腓總神經。' },
  { id: 'p_radic', name: '疑似神經根壓迫', region: ['lspine'], src: '補充：一般臨床鑑別', refer: true,
    desc: '直腿抬高很低角度就放射到小腿或腳、伴麻木或無力，可能為腰椎間盤／神經根問題。',
    t: { t_slr_low: 4, t_nerve: 2, r_weak: 2 },
    tight: [], weak: [], points: [], chain: ['lspine', 'hip', 'knee', 'ankle'],
    tech: '建議先轉介就醫確認；推拿以周邊肌肉放鬆為主，避免強力扭轉或重壓腰椎。' },
  { id: 'p_acute', name: '急性腰閃傷（A＋IN，痛側在下）', region: ['lspine', 'pelvis', 'sacrum'], src: '課堂筆記（椎間盤／急性腰閃傷）',
    desc: '筆記：急性腰閃傷的三種來源——髂腰橫韌帶、腰椎滑膜嵌頓、肌肉拉傷。外觀：對側臀部後突、身體向痛側側彎（痛側在下），骨盆變成 A＋IN。',
    t: { c_lbp_acute: 4, o_lean_down: 3, c_lbp: 1, t_psis_high: 1, t_psis_near: 1 },
    tight: [['ql', 'same', 3], ['erector', 'same', 2], ['multifidus', 'same', 2], ['iliopsoas', 'same', 1], ['deep_rot', 'same', 1]],
    weak: [['glute_med', 'opp', 1]],
    points: ['BL52', 'BL23', 'GV26', 'BL40', 'SI3'], chain: ['pelvis', 'lspine', 'sacrum'],
    tech: '急性期：遠端穴（委中、後溪、水溝）配合慢慢活動腰，局部不重壓；之後側臥沿髂嵴上緣放鬆腰方肌，再依第一角度 A、第二角度 IN 的順序重新量骨盆。' },
  { id: 'p_disc', name: '椎間盤型下背痛（慢性，痛側在上）', region: ['lspine', 'hip'], src: '課堂筆記（椎間盤）', refer: true,
    desc: '筆記：椎間盤屬慢性，分肩上型、肩下型（突出物在神經根的上方或下方），外觀為「痛側在上」。合併直腿抬高很低就放射、麻木或無力時先轉介。',
    t: { o_lean_up: 4, c_sciatic: 2, t_slr_low: 2, c_lbp: 1, t_nerve: 1 },
    tight: [['ql', 'opp', 1], ['erector', 'both', 1], ['iliopsoas', 'same', 1]], weak: [],
    points: ['BL23', 'BL25', 'BL40', 'GB30'], chain: ['lspine', 'hip', 'knee', 'ankle'],
    tech: '以周邊肌肉放鬆為主，避免強力扭轉與重壓腰椎；麻的位置可對照知識庫「腰薦神經分布」推估節段。' },
  { id: 'p_ql', name: '腰方肌型下背痛', region: ['lspine', 'pelvis'], src: '補充：肌動學',
    desc: '腰側深層痛，彎腰轉身時卡、起身困難；常伴同側骨盆高。',
    t: { c_lbp: 2, o_crest_high: 2, c_lbp_acute: 1, t_heel_short: 1 },
    tight: [['ql', 'same', 3], ['erector', 'same', 2], ['iliopsoas', 'same', 1]],
    weak: [['glute_med', 'opp', 1]],
    points: ['BL52', 'BL23', 'BL40'], chain: ['pelvis', 'lspine'],
    tech: '側臥沿髂嵴上緣放鬆腰方肌；同時檢查骨盆高低（第一、第三角度）。' },
  { id: 'p_scap_pelvis', name: '肩胛問題來自骨盆（坐→臥肩胛會變）', region: ['scap', 'pelvis', 'sacrum'], src: '課堂筆記（骨盆＆肩胛）',
    desc: '筆記：坐姿轉臥姿，肩胛相對位置改變 → 跟骨盆有關；肩胛位置不變、骨盆也是正的 → 問題在肩關節本身。檢查流程：坐、臥看肩胛 → 薦椎 ← 骨盆（A/P、EX/IN、③EX/IN 取最大角度）← 股骨 ← 脛腓 ← 距骨 ← 足跟（後足）← 中足、前足。',
    t: { t_scap_sitlie: 4, o_sh_high: 1, o_crest_high: 1 },
    tight: [['lat', 'same', 2], ['ql', 'same', 1], ['glute_max', 'opp', 1]], weak: [],
    points: ['BL17', 'BL23', 'GB21'], chain: ['pelvis', 'sacrum', 'lspine', 'scap'],
    tech: '先處理骨盆（找最大的那個角度），再回頭看肩胛；由下往上依序檢查足→距骨→脛腓→股骨→骨盆。' },
  { id: 'p_scap_local', name: '肩胛／肩關節本身問題（坐→臥不變）', region: ['shoulder', 'scap'], src: '課堂筆記（骨盆＆肩胛）',
    desc: '筆記：坐姿轉臥姿肩胛相對位置不變、骨盆是正位 → 問題在肩關節。肩胛胸廓關節是平面關節，相關肌：豎脊肌、胸髂肋肌、肩胛下肌、前鋸肌。',
    t: { t_scap_same: 4, c_sh_raise: 1, c_sh_front: 1 },
    tight: [['subscap', 'same', 2], ['serratus', 'same', 2], ['pec_minor', 'same', 1], ['levator', 'same', 1], ['rhomboid', 'same', 1]], weak: [],
    points: ['SI11', 'SI9', 'LI15', 'TE14'], chain: ['shoulder', 'elbow'],
    tech: '肩胛動作對應肌（筆記）：上提＝上斜方、提肩胛、菱形；下壓＝下斜方、闊背、鎖骨下、胸小；前突＝前鋸；後縮＝中斜方、菱形；上旋＝上下斜方、前鋸；下旋＝菱形、胸小。找出受限方向對應的肌肉處理。' },
  { id: 'p_headfwd', name: '頭前傾／上交叉', region: ['cspine', 'occ', 'tspine'], src: '課堂 0810（胸鎖乳突肌槓桿）、補充',
    desc: '耳垂落在肩峰前方。胸鎖乳突肌與枕下肌群縮短、深層頸屈肌與下斜方無力；常合併圓肩。',
    t: { o_head_fwd: 3, c_head_back: 2, c_neckstiff: 1, o_round: 1, o_kyph: 1 },
    tight: [['subocc', 'both', 3], ['scm', 'both', 2], ['trap_u', 'both', 2], ['levator', 'both', 1], ['pec_minor', 'both', 2], ['scalene', 'both', 1]],
    weak: [['trap_l', 'both', 2], ['rhomboid', 'both', 1], ['trap_m', 'both', 1]],
    points: ['GB20', 'BL10', 'GV16', 'GB21'], chain: ['occ', 'tspine', 'scap'],
    tech: '枕下放鬆（仰臥指腹勾住枕骨下緣）→ 胸鎖乳突肌拿捏 → 胸小肌 → 最後才處理上斜方。' },
  { id: 'p_round', name: '圓肩／胸小肌緊', region: ['scap', 'shoulder'], src: '課堂 0810、補充',
    desc: '胸小肌把肩胛骨往前下拉（前傾），胸大肌讓肱骨內旋；背部菱形肌、中斜方被拉長而痠痛。',
    t: { o_round: 3, t_pecmin: 3, c_scap_between: 2, c_arm_numb: 1, o_kyph: 1 },
    tight: [['pec_minor', 'same', 3], ['pec_major', 'same', 2], ['serratus', 'same', 1]],
    weak: [['rhomboid', 'same', 2], ['trap_m', 'same', 2], ['trap_l', 'same', 1]],
    points: ['LU1', 'LU2', 'CV17', 'BL43'], chain: ['shoulder', 'tspine'],
    tech: '肩胛間痛多是「被拉長的痛」：別只揉背，先鬆前面的胸小肌、胸大肌，再強化背部。' },
  { id: 'p_shhigh', name: '高低肩（上提側緊）', region: ['scap', 'cspine'], src: '課堂 0727（觀察）、補充',
    desc: '高側上斜方、提肩胛肌緊；亦要往下看骨盆與腰椎側彎（下面歪上面跟著歪）。',
    t: { o_sh_high: 3, c_neckstiff: 1, o_head_tilt: 1, t_neck_rot: 1 },
    tight: [['trap_u', 'same', 3], ['levator', 'same', 3], ['scalene', 'same', 1]],
    weak: [['trap_l', 'same', 1], ['lat', 'same', 1]],
    points: ['GB21', 'SI14', 'TE15', 'SI13'], chain: ['cspine', 'tspine', 'lspine', 'pelvis'],
    tech: '拿肩井、點按肩胛上角（提肩胛止點）。若骨盆也高低，先處理骨盆再回頭看肩。' },
  { id: 'p_stiffneck', name: '落枕／頸部轉動受限', region: ['cspine'], src: '補充：經穴',
    desc: '頭轉不過去、肩胛上角痛，多為提肩胛肌與胸鎖乳突肌痙攣。',
    t: { t_neck_rot: 3, c_neck: 2, c_neckstiff: 1 },
    tight: [['levator', 'same', 3], ['scm', 'same', 2], ['splenius', 'same', 2], ['trap_u', 'same', 1]],
    weak: [],
    points: ['SI3', 'GB39', 'SI14', 'GB20', 'LU7'], chain: ['scap'],
    tech: '先遠端：按後溪或懸鐘，同時請客人慢慢轉頭；再局部放鬆提肩胛肌附著點，避免直接強力扳頸。' },
  { id: 'p_tos', name: '手麻：胸廓出口（斜角肌／胸小肌）', region: ['cspine', 'shoulder'], src: '課堂 0727（鎖骨下、胸小肌）、補充',
    desc: '臂神經叢與鎖骨下動脈會經過斜角肌之間、鎖骨下方與胸小肌下方；這些地方緊會造成手麻。',
    t: { c_arm_numb: 3, t_scalene: 3, t_pecmin: 2, o_round: 1, o_head_fwd: 1 },
    tight: [['scalene', 'same', 3], ['pec_minor', 'same', 3], ['scm', 'same', 1]],
    weak: [],
    points: ['ST12', 'LU1', 'HT1', 'PC6'], chain: ['shoulder', 'elbow'],
    tech: '輕柔放鬆斜角肌（勿重壓缺盆），胸小肌放鬆；若麻在拇指～中指且夜間加重，也要檢查腕隧道（內關、大陵）。' },
  { id: 'p_cuff', name: '肩痛／旋轉肌袖、五十肩', region: ['shoulder', 'scap'], src: '課堂 0907、補充',
    desc: '舉手痛、睡覺壓肩痛；撕裂常在靠近關節處，多由肌肉不平衡長期拉扯造成。外旋受限明顯時考慮五十肩（肩胛下肌）。',
    t: { c_sh_raise: 3, c_sh_front: 2, t_infra: 3, t_joint: 1 },
    tight: [['infraspinatus', 'same', 2], ['subscap', 'same', 2], ['supraspinatus', 'same', 2], ['pec_minor', 'same', 2], ['teres_major', 'same', 1], ['lat', 'same', 1]],
    weak: [['trap_l', 'same', 1], ['serratus', 'same', 1]],
    points: ['LI15', 'TE14', 'SI9', 'SI11', 'ST38'], chain: ['scap', 'tspine'],
    tech: '天宗（棘下）、肩貞（小圓／大圓）、喙突下（胸小肌）依序處理；遠端條口配合活動肩。關節被動也受限且痛 → 骨／關節問題，避免強拉。' },
  { id: 'p_tennis', name: '網球肘（外上髁）', region: ['elbow'], src: '補充：肌動學',
    desc: '前臂伸肌總腱過度使用。', t: { c_elbow_lat: 3, c_wrist: 1 },
    tight: [['forearm_ext', 'same', 3], ['brachiorad', 'same', 2]], weak: [],
    points: ['LI11', 'LI10', 'TE5'], chain: ['shoulder', 'wrist'],
    tech: '彈撥外上髁下 2–3 指的肌腹（不是壓骨頭），並檢查肩胛穩定度（肩不穩時手肘代償）。' },
  { id: 'p_golfer', name: '高爾夫球肘／腕屈肌緊', region: ['elbow', 'wrist'], src: '補充：肌動學',
    desc: '前臂屈肌總腱過度使用，常伴手腕痛、手麻。', t: { c_elbow_med: 3, c_wrist: 1, c_arm_numb: 1 },
    tight: [['forearm_flex', 'same', 3]], weak: [], points: ['HT3', 'PC3', 'PC6'], chain: ['shoulder', 'wrist'],
    tech: '由腕往肘推前臂掌側，內上髁下方撥揉；腕伸展。' },
  { id: 'p_itb', name: '跑者膝（髂脛束摩擦）', region: ['knee', 'hip'], src: '課堂 0810、0907',
    desc: '膝外側痛。膝蓋是受害者：股骨內外轉（骨盆第二角度）改變髂脛束經過股骨外髁的角度而產生摩擦。',
    t: { c_knee_lat: 3, t_itb: 3, c_thigh_lat: 2, t_troch_thin: 1, t_psis_near: 1 },
    tight: [['tfl_itb', 'same', 3], ['vastus_lat', 'same', 2], ['glute_max', 'same', 1]],
    weak: [['glute_med', 'same', 1]],
    points: ['GB31', 'GB33', 'GB29', 'GB34'], chain: ['hip', 'pelvis'],
    tech: '先調整骨盆／股骨旋轉（EX/IN），再放鬆闊筋膜張肌與股外側肌；只推膝外側效果有限。' },
  { id: 'p_kneefront', name: '膝前痛（髕骨軌跡）', region: ['knee'], src: '課堂 0907、補充',
    desc: '上下樓梯、蹲下膝前痛。股直肌緊（骨盆前傾）、股外側肌強於股內側肌，髕骨被拉向外。',
    t: { c_knee_front: 3, o_lordosis: 1, o_knee_x: 1 },
    tight: [['rectus_fem', 'same', 3], ['vastus_lat', 'same', 2], ['tfl_itb', 'same', 1]],
    weak: [['vastus_med', 'same', 2]],
    points: ['ST34', 'ST35', 'SP10', 'ST32'], chain: ['hip', 'ankle'],
    tech: '依課堂順序：①先看上面（骨盆／髖）②再看下面（踝／距骨）③都沒問題才處理膝本身。' },
  { id: 'p_kneemed', name: '膝內側痛（鵝足／內側半月板）', region: ['knee'], src: '課堂 0907、0914',
    desc: '鵝足＝縫匠肌、股薄肌、半腱肌共同止點。若膝越彎越痛、會卡住，需懷疑內側半月板（內側最常受傷）。',
    t: { c_knee_med: 3, t_pes: 3, t_knee_flex: 2, o_knee_x: 1 },
    tight: [['sartorius', 'same', 2], ['adductors', 'same', 2], ['hamstrings', 'same', 2]],
    weak: [['vastus_med', 'same', 1]],
    points: ['SP9', 'LR8', 'SP10', 'KI10'], chain: ['hip', 'ankle'],
    tech: '鵝足靠近肌腱附著處，不可重壓、不可局部大力（課堂提醒）；從三條肌肉的肌腹往上放鬆。半月板疑慮先轉介。' },
  { id: 'p_meniscus', name: '疑似半月板損傷', region: ['knee'], src: '課堂 0907、0914', refer: true,
    desc: '膝越彎越痛、強痛，或會卡住（另兩個卡住原因：關節鼠、軟組織碎片）。',
    t: { t_knee_flex: 4, c_knee_med: 1, c_knee_back: 1 },
    tight: [], weak: [], points: [], chain: ['knee'],
    tech: '建議轉介確認。推拿只處理膝周圍肌肉（膕肌、膕繩肌）與上下關節。' },
  { id: 'p_kneeback', name: '膝後痛（膕肌、膕窩韌帶）', region: ['knee'], src: '課堂 0907',
    desc: '膕肌在膝彎曲約 30° 時開始讓脛骨旋轉（解鎖膝蓋）；膕窩韌帶發炎造成膝後痛。',
    t: { c_knee_back: 3, t_knee_flex: 1 },
    tight: [['gastroc', 'same', 2], ['hamstrings', 'same', 2]], weak: [],
    points: ['BL40', 'KI10', 'BL39'], chain: ['knee', 'ankle'],
    tech: '輕揉委中周圍（有血管神經），配合膝屈伸與脛骨內外轉被動活動。' },
  { id: 'p_ankle', name: '踝扭傷後遺（活動度下降、往上代償）', region: ['ankle', 'knee'], src: '課堂 0907',
    desc: '踝扭傷後活動角度變小（例如 90° 只剩 75°），上面的膝、腰、肩必須多轉來補，久了出現他處受傷（課堂舉投手腳踝受傷後肩傷的例子）。',
    t: { c_ankle: 3, t_df_limited: 2, c_knee_front: 1, c_calf: 1 },
    tight: [['peroneus', 'same', 2], ['gastroc', 'same', 2], ['soleus', 'same', 2], ['tib_ant', 'same', 1]],
    weak: [['peroneus', 'same', 1]],
    points: ['GB40', 'BL60', 'KI3', 'ST41', 'BL62'], chain: ['knee', 'hip', 'lspine'],
    tech: '恢復距骨滑動與踝背屈：放鬆小腿後側、腓骨肌，丘墟／崑崙周圍輕揉。' },
  { id: 'p_flat', name: '扁平足／足底筋膜炎', region: ['foot', 'ankle'], src: '課堂 0907、補充',
    desc: '足弓是承重的彈簧，塌陷後避震變差，往上影響膝、髖。鞋墊只是幫助，要訓練脛前、脛後肌。',
    t: { o_flatfoot: 3, c_heel: 3, c_calf: 1, o_knee_x: 1 },
    tight: [['gastroc', 'same', 2], ['soleus', 'same', 2], ['plantar', 'same', 2], ['peroneus', 'same', 1]],
    weak: [['tib_post', 'same', 2], ['tib_ant', 'same', 1]],
    points: ['KI1', 'KI2', 'SP4', 'BL57', 'KI3'], chain: ['ankle', 'knee'],
    tech: '足底由跟往趾推、小腿後側放鬆；足弓內側（公孫、然谷）找緊點。' },
  { id: 'p_trend', name: '臀中肌無力（走路骨盆晃）', region: ['pelvis', 'hip'], src: '補充：肌動學',
    desc: '單腳站時對側骨盆下掉（Trendelenburg）＝站立腳的臀中肌無力。', t: { t_trend: 4, c_si: 1, c_knee_lat: 1 },
    tight: [['ql', 'opp', 2], ['tfl_itb', 'same', 1]], weak: [['glute_med', 'same', 3]],
    points: ['GB29', 'GB30'], chain: ['knee', 'lspine'], tech: '放鬆對側腰方肌，強化站立側臀中肌（側躺抬腿）。' },
  { id: 'p_kyph', name: '駝背／胸椎後凸', region: ['tspine'], src: '課堂 0810、補充',
    desc: '前側肌群（胸大肌、腹直肌）縮短，背部伸肌被拉長；會把頭往前帶。', t: { o_kyph: 3, c_scap_between: 1, c_chest: 1 },
    tight: [['pec_major', 'both', 2], ['rectus_abd', 'both', 2], ['pec_minor', 'both', 1]],
    weak: [['erector', 'both', 1], ['trap_m', 'both', 1], ['trap_l', 'both', 1]],
    points: ['CV17', 'BL13', 'BL15', 'GV12'], chain: ['cspine', 'scap', 'diaphragm'],
    tech: '開胸（胸大肌、膻中）、腹直肌上段放鬆，再處理胸椎；呼吸時肋骨要能擴張。' },
  { id: 'p_breath', name: '呼吸淺／橫膈緊', region: ['diaphragm', 'tspine'], src: '課堂 0727、筆記（呼吸波）',
    desc: '吸氣時橫膈下降，薦椎微向後（反點頭）、骨盆下口打開；呼吸受限也會影響薦椎的呼吸波。',
    t: { c_chest: 3, o_kyph: 1, o_head_fwd: 1 },
    tight: [['diaphragm', 'both', 2], ['scalene', 'both', 2], ['pec_minor', 'both', 1]], weak: [],
    points: ['CV17', 'BL17', 'LR14', 'CV12'], chain: ['sacrum', 'tspine'],
    tech: '吐氣時沿肋弓下緣勾住橫膈、吸氣時維持；整復時可配合呼吸（吸氣準備、吐氣時施力）。' },
  { id: 'p_tmj', name: '顳顎關節／咬肌緊', region: ['head'], src: '補充', t: { c_jaw: 3, c_head_side: 1 },
    desc: '咬肌、顳肌緊；與上頸、胸鎖乳突肌相互影響。',
    tight: [['masseter', 'same', 3], ['temporalis', 'same', 2], ['scm', 'same', 1]], weak: [],
    points: ['ST6', 'ST7', 'SI19', 'TE17', 'LI4'], chain: ['cspine'], tech: '指腹圓揉頰車、下關，張口時往下推。' },
  // 頭痛分類（課堂筆記）
  { id: 'p_h_front', name: '前額頭痛（陽明）', region: ['head'], src: '課堂筆記（頭痛）', t: { c_head_front: 4 },
    desc: '筆記：前額痛屬胃（陽明）。', tight: [['scm', 'both', 1], ['subocc', 'both', 1]], weak: [], points: ['ST8', 'EX-HN3', 'LI4', 'ST44', 'BL2'], chain: ['cspine'],
    tech: '頭維、印堂、攢竹局部，合谷、內庭遠端；胸鎖乳突肌也會轉移痛到前額。' },
  { id: 'p_h_side', name: '偏頭痛（少陽）', region: ['head'], src: '課堂筆記（頭痛、足少陽經筋）', t: { c_head_side: 4 },
    desc: '筆記：偏頭痛屬膽（少陽）；足少陽經筋病「偏頭痛、維筋相交」。', tight: [['temporalis', 'same', 2], ['trap_u', 'same', 2], ['splenius', 'same', 1]], weak: [],
    points: ['GB8', 'EX-HN5', 'GB20', 'TE5', 'GB41'], chain: ['cspine', 'scap'], tech: '率谷、太陽、風池；上斜方肌常轉移痛到太陽穴。' },
  { id: 'p_h_back', name: '後頭痛（太陽）', region: ['head', 'occ'], src: '課堂筆記（頭痛）', t: { c_head_back: 4, o_head_fwd: 1 },
    desc: '筆記：後頭痛屬膀胱（太陽）。', tight: [['subocc', 'both', 3], ['splenius', 'both', 2], ['trap_u', 'both', 1]], weak: [],
    points: ['BL10', 'GB20', 'GV16', 'BL60', 'SI3'], chain: ['cspine'], tech: '天柱、風池、風府，崑崙、後溪遠端。' },
  { id: 'p_h_top', name: '巔頂痛（肝）', region: ['head'], src: '課堂筆記（頭痛）', t: { c_head_top: 4 },
    desc: '筆記：巔頂痛屬肝；中心向外（往耳）屬腎；重著悶痛屬脾。', tight: [['splenius', 'both', 1]], weak: [],
    points: ['GV20', 'LR3', 'KI1'], chain: [], tech: '百會、太衝。' },
];

/* 連鎖關係：節點位置在 220×460 的人形座標上（前視） */
window.CHAIN_NODES = [
  { id: 'head', name: '頭／顳顎', x: 110, y: 34 }, { id: 'occ', name: '上頸／枕下', x: 110, y: 72 }, { id: 'cspine', name: '頸椎', x: 110, y: 96 },
  { id: 'scap', name: '肩胛骨', x: 66, y: 132, lab: 'r', dy: 12 }, { id: 'shoulder', name: '肩關節', x: 34, y: 120 }, { id: 'elbow', name: '手肘', x: 22, y: 196 }, { id: 'wrist', name: '手腕／手', x: 16, y: 262 },
  { id: 'tspine', name: '胸椎／肋骨', x: 110, y: 150 }, { id: 'diaphragm', name: '橫膈／呼吸', x: 148, y: 186 }, { id: 'lspine', name: '腰椎', x: 110, y: 214 },
  { id: 'sacrum', name: '薦椎', x: 110, y: 250 }, { id: 'pelvis', name: '骨盆（無名骨）', x: 160, y: 240 }, { id: 'pubis', name: '恥骨聯合', x: 110, y: 276 }, { id: 'hip', name: '髖關節', x: 66, y: 272 },
  { id: 'knee', name: '膝', x: 74, y: 352 }, { id: 'ankle', name: '踝／距骨', x: 76, y: 428 }, { id: 'foot', name: '足弓', x: 150, y: 446 },
];
window.CHAIN_EDGES = [
  { a: 'foot', b: 'ankle', how: '足弓塌陷時距骨內旋、跟骨外翻，踝內側承受更多壓力；足弓的彈性是承重的避震器。', src: '課堂 0727、0907' },
  { a: 'foot', b: 'knee', how: '足外翻（旋前、足弓塌）常與整條下肢內轉、X 型腿同時出現；足內翻（旋後、高弓）則與下肢外轉、O 型腿一起。', src: '課堂 0928-2' },
  { a: 'ankle', b: 'knee', how: '踝扭傷後活動度變小（90°→75°），脛骨只好用旋轉補角度，膝關節被扭轉而受傷——膝是受害者。', src: '課堂 0907' },
  { a: 'ankle', b: 'lspine', how: '踝角度不夠，上面的腰必須多轉；轉不夠就再往上由肩、手代償（課堂舉投手腳踝傷後肩傷）。', src: '課堂 0907' },
  { a: 'knee', b: 'hip', how: 'O 型／X 型腿改變股骨與脛骨夾角（正常約 170–175°），股骨旋轉跟著改變，影響髖與骨盆。', src: '課堂 0907' },
  { a: 'hip', b: 'knee', how: '股骨內轉／外轉（第二角度 IN/EX）改變髂脛束經過膝外側的角度 → 跑者膝；也改變髕骨軌跡。', src: '課堂 0810、0907' },
  { a: 'pelvis', b: 'hip', how: '無名骨旋轉改變髖臼方向，股骨跟著內外轉；大轉子厚薄、屈膝足跟方向都會改變。', src: '課堂 0810' },
  { a: 'pelvis', b: 'sacrum', how: '很多時候是骨盆先歪，薦椎卡在兩塊無名骨中間跟著歪；薦髂關節前下為滑液關節、後上為纖維（韌帶）連結。', src: '課堂筆記（薦椎）' },
  { a: 'sacrum', b: 'lspine', how: '薦椎是腰椎的底座：L5 下關節突卡在 S1 的兩個凹槽裡防止前滑，所以薦椎歪了，上面的腰椎一定跟著轉、跟著歪。只敲腰椎矯正側彎是不夠的。', src: '課堂 0727、筆記' },
  { a: 'pelvis', b: 'lspine', how: '第一角度（A/P）→ 腰椎前凸增加或變平；第二角度（EX/IN）→ 脊椎旋轉；第三角度（耳狀面 EX/IN）→ 腰椎直接側彎（無旋轉）。急性腰閃傷常見 A＋IN、向痛側側彎。', src: '課堂 0817、筆記' },
  { a: 'pelvis', b: 'pubis', how: '第三角度（耳狀面外展 EX／內收 IN）常造成恥骨聯合高低、鼠蹊痛；③ IN 相關的是內收肌群（內收大、長、短肌、恥骨肌、股薄肌）。懷孕時鬆弛素使韌帶鬆，骨盆更容易歪。', src: '課堂 0727、0817、筆記' },
  { a: 'pelvis', b: 'knee', how: '第一角度 A 側長腳、P 側短腿；第三角度 EX 在股骨不動時等於把腳往上帶 → 短腿。兩膝受力不均。', src: '課堂 0817、筆記' },
  { a: 'foot', b: 'pelvis', how: '筆記：中軸力線 → 骨盆分力 → 股骨 → … → 足底，再回傳往上 → 薦髂與骨盆環。檢查由下往上：前中足 → 足跟 → 距骨 → 脛腓 → 股骨 → 骨盆 → 薦椎。', src: '課堂筆記（骨盆＆肩胛）' },
  { a: 'sacrum', b: 'cspine', how: '筆記「兄弟椎」：C1↔L5、C2↔L4、C3↔L3、C4↔L2、C5↔L1 互相對應；「父母椎」：尾骨 → 薦椎五節 → 上面各段脊椎。頸部問題可往薦尾找源頭。', src: '課堂筆記（父母椎力學）' },
  { a: 'lspine', b: 'tspine', how: '腰椎旋轉或側彎時，胸椎往反方向代償（S 型），轉折點多在胸腰交界（T12–L1）或 T9–T10 附近，觸診找轉折點。', src: '課堂 0810' },
  { a: 'tspine', b: 'cspine', how: '胸椎後凸增加 → 頭往前帶（頭前傾）；上胸椎與頸椎一起代償。', src: '補充：肌動學' },
  { a: 'tspine', b: 'scap', how: '胸椎後凸讓肩胛骨外展、前傾（圓肩），肩胛貼不住胸廓。', src: '補充：肌動學' },
  { a: 'scap', b: 'shoulder', how: '胸小肌把肩胛往前下拉（前傾），肩峰下空間變小 → 肩夾擠；肩胛位置不對，旋轉肌袖長期被拉扯而在靠關節處撕裂。', src: '課堂 0810、0907' },
  { a: 'shoulder', b: 'elbow', how: '肩活動度不足時，手肘與前臂代償過度使用（網球肘、高爾夫球肘）。', src: '補充' },
  { a: 'cspine', b: 'wrist', how: '斜角肌、鎖骨下、胸小肌下方是臂神經叢與鎖骨下動脈的通道，緊縮造成手麻（胸廓出口）。', src: '課堂 0727、補充' },
  { a: 'scap', b: 'cspine', how: '提肩胛肌、上斜方連接肩胛與頸椎：高低肩與頸部轉動受限互相牽動。', src: '補充' },
  { a: 'tspine', b: 'cspine', how: '肋骨隨胸椎旋轉時，附著在第 1、2 肋的斜角肌一邊緊一邊鬆，把頸椎拉歪或讓頭轉向；椎動脈在頸椎橫突孔內，扭轉可能影響腦部供血（部分偏頭痛）。', src: '課堂 0928-2' },
  { a: 'cspine', b: 'occ', how: '頭前傾時上頸過度伸直，枕下肌群縮短 → 後頭痛、頭暈、眼睛疲勞。胸鎖乳突肌緊也會把頭拉向前（支點與槓桿）。', src: '課堂 0810' },
  { a: 'occ', b: 'head', how: '枕下肌群、頭夾肌、上斜方的轉移痛分布在頭兩側、眼後、太陽穴。', src: '補充' },
  { a: 'diaphragm', b: 'sacrum', how: '呼吸波：吸氣橫膈下降、兩坐骨靠近、薦椎微向後（反點頭），骨盆下口變大；吐氣相反。呼吸軸在 S1。', src: '課堂筆記（薦椎）' },
  { a: 'diaphragm', b: 'tspine', how: '橫膈附著於下肋與 L1–L3，呼吸受限讓肋骨與胸腰交界活動變差。', src: '補充' },
  { a: 'scap', b: 'pelvis', how: '人體「四大平衡」：兩塊肩胛骨與兩塊無名骨。脊椎插在骨盆上、上面掛著兩個肩胛；對角線（例如右肩與左髖）透過闊背肌、胸腰筋膜、臀大肌互相牽動。', src: '課堂 0727' },
  { a: 'head', b: 'ankle', how: '足少陽經筋「維筋相交」：左額角傷 → 右足不能行（與陰陽蹻平衡有關，左右交叉）。', src: '課堂筆記（經筋）' },
  { a: 'cspine', b: 'elbow', how: '筆記：手三陽（大腸、三焦、小腸經筋）與 C2 的關係很大；手臂外側、背側問題可往上頸查。', src: '課堂筆記（經筋）' },
];
